const fs=require('fs'),path=require('path'),puppeteer=require('puppeteer-core');
const BASE=process.env.PHASE21_BASE||'http://127.0.0.1:8000/';
const OUT=process.env.PHASE21_OUT||'/tmp/phase21-review/spotcheck';
const SHOTS=path.join(OUT,'screenshots');fs.mkdirSync(SHOTS,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const routes=['index.html','corporate.html','energy.html','products.html','product.html','urea-46.html','caustic-soda-solid.html','sodium-sulphate-anhydrous.html','sales.html','technology.html','evidence-axis.html','ventures.html','contact.html','privacy.html','legal.html','404.html'];
const critical=['index.html','products.html','sales.html','technology.html','contact.html'];
const views=[[1920,1080],[1440,900],[768,1024],[390,844],[360,800]];
const spots=[];for(const r of critical)for(const [w,h] of views)spots.push({route:r,w,h});for(const r of ['corporate.html','evidence-axis.html','ventures.html','privacy.html','legal.html'])spots.push({route:r,w:390,h:844});
const safe=s=>s.replace(/\.html$/,'').replace(/[^a-z0-9-]/gi,'_');
async function pageFor(browser,w,h){const p=await browser.newPage();await p.setViewport({width:w,height:h,deviceScaleFactor:1});await p.setCacheEnabled(false);return p}
async function prime(page){await page.evaluate(async()=>{const step=Math.max(300,Math.floor(innerHeight*.7));for(let y=0;y<document.documentElement.scrollHeight;y+=step){scrollTo(0,y);await new Promise(r=>setTimeout(r,55))}scrollTo(0,0)});await sleep(120)}
async function inspect(page){return page.evaluate(()=>{const d=document.documentElement,main=document.querySelector('main'),h1=main?.querySelectorAll('h1').length||0,footer=document.querySelector('.site-footer,footer'),nav=document.querySelector('.primary-nav');const visible=e=>{if(!e)return false;const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};return {title:document.title,main:!!main,h1,footer:!!footer,nav:!!nav,overflow:d.scrollWidth>d.clientWidth+1,scrollWidth:d.scrollWidth,clientWidth:d.clientWidth,bodyHeight:document.body.scrollHeight,hasVisibleNav:visible(nav)};})}
async function load(browser,route,w,h,full=true){const p=await pageFor(browser,w,h),consoleErrors=[],pageErrors=[],sameOriginFailures=[],externalFailures=[],assetBad=[];p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});p.on('pageerror',e=>pageErrors.push(String(e)));p.on('requestfailed',r=>{const x={url:r.url(),error:r.failure()?.errorText||''};try{new URL(r.url()).origin===new URL(BASE).origin?sameOriginFailures.push(x):externalFailures.push(x)}catch{externalFailures.push(x)}});p.on('response',r=>{try{const u=new URL(r.url()),base=new URL(BASE);if(u.origin===base.origin&&r.status()>=400&&(/\.css(?:$|\?)/.test(u.pathname+u.search)||/\.js(?:$|\?)/.test(u.pathname+u.search)))assetBad.push({url:r.url(),status:r.status()})}catch{}});let status=0;try{const resp=await p.goto(BASE+route,{waitUntil:'load',timeout:45000});status=resp?.status()||0}catch(e){pageErrors.push('navigation '+String(e))}await sleep(route==='index.html'?900:250);const visual=await inspect(p);if(full){await prime(p);const file=`${safe(route)}-${w}x${h}.png`;await p.screenshot({path:path.join(SHOTS,file),fullPage:true});await p.close();return {route,w,h,status,consoleErrors,pageErrors,sameOriginFailures,externalFailures,assetBad,visual,file}}await p.close();return {route,w,h,status,consoleErrors,pageErrors,sameOriginFailures,externalFailures,assetBad,visual}}
const valid=x=>x.status===200&&!x.pageErrors.length&&!x.sameOriginFailures.length&&!x.assetBad.length&&!x.visual.overflow&&x.visual.main&&x.visual.h1===1&&x.visual.footer&&x.visual.nav;
async function focusVisible(page,sel){return page.evaluate(s=>{const e=document.querySelector(s);if(!e)return {pass:false,reason:'missing'};e.focus();e.scrollIntoView({block:'center'});const cs=getComputedStyle(e),r=e.getBoundingClientRect();const ring=(cs.outlineStyle!=='none'&&cs.outlineWidth!=='0px')||cs.boxShadow!=='none';return {pass:document.activeElement===e&&r.width>0&&r.height>0&&ring,outline:`${cs.outlineStyle} ${cs.outlineWidth}`,boxShadow:cs.boxShadow};},sel)}
async function interactions(browser){const out=[];let p;
 p=await pageFor(browser,1440,900);await p.goto(BASE+'index.html',{waitUntil:'load'});out.push({name:'desktop-navigation',pass:await p.evaluate(()=>{const n=document.querySelector('.primary-nav');return !!n&&getComputedStyle(n).display!=='none'&&[...n.querySelectorAll('a[href]')].length>=5})});await p.close();
 p=await pageFor(browser,390,844);await p.goto(BASE+'index.html',{waitUntil:'load'});const menu=await p.$('.menu-toggle');if(!menu)out.push({name:'compact-navigation',pass:false,reason:'menu missing'});else{await menu.click();await sleep(120);const open=await p.evaluate(()=>({open:document.querySelector('.primary-nav')?.classList.contains('is-open'),expanded:document.querySelector('.menu-toggle')?.getAttribute('aria-expanded'),firstFocused:document.activeElement?.closest('.primary-nav')!==null}));await p.keyboard.press('Escape');await sleep(80);const closed=await p.evaluate(()=>({open:document.querySelector('.primary-nav')?.classList.contains('is-open'),expanded:document.querySelector('.menu-toggle')?.getAttribute('aria-expanded'),focusRestored:document.activeElement===document.querySelector('.menu-toggle')}));out.push({name:'compact-navigation-escape-focus',pass:open.open&&open.expanded==='true'&&open.firstFocused&&!closed.open&&closed.expanded==='false'&&closed.focusRestored,open,closed})}await p.close();
 p=await pageFor(browser,390,844);await p.goto(BASE+'corporate.html',{waitUntil:'load'});await p.keyboard.press('Tab');await sleep(50);const skip=await p.evaluate(()=>{const e=document.activeElement,s=e?getComputedStyle(e):null,r=e?.getBoundingClientRect();return {pass:!!e?.classList.contains('skip-link')&&r.width>0&&r.height>0&&s.visibility!=='hidden',tag:e?.tagName,cls:e?.className}});out.push({name:'skip-link',...skip});await p.close();
 p=await pageFor(browser,1440,900);await p.goto(BASE+'contact.html',{waitUntil:'load'});const ctaSel='main a.button-link, main a.contact-card, main a[href]';out.push({name:'cta-keyboard-focus',...(await focusVisible(p,ctaSel))});await p.close();
 p=await pageFor(browser,390,844);await p.goto(BASE+'sales.html',{waitUntil:'load'});const labels=await p.evaluate(()=>{const controls=[...document.querySelectorAll('#rfq-builder input,#rfq-builder textarea,#rfq-builder select')];return {count:controls.length,unlabelled:controls.filter(e=>!e.id||!document.querySelector(`label[for="${CSS.escape(e.id)}"]`)).map(e=>e.id||e.name)}});const long='Long Phase 21 RFQ requirement — '+('1234567890 '.repeat(12));await p.type('#rfq-product','Urea 46');await p.type('#rfq-grade','46% nitrogen granular');await p.type('#rfq-quantity',long);await p.type('#rfq-destination','Istanbul, Türkiye');await p.type('#rfq-timing','Q4 2026');await p.type('#rfq-specification','Technical requirement '+long);await p.type('#rfq-contact-name','Phase 21 Reviewer');await p.type('#rfq-company','Unique Holding QA');await p.type('#rfq-email','review@example.com');await p.type('#rfq-phone','+90 212 727 22 22');await p.type('#rfq-notes','Release candidate interaction check');await sleep(80);const filled=await p.evaluate(()=>{const a=document.querySelector('#rfq-email-action'),d=document.documentElement;return {href:a?.getAttribute('href')||'',overflow:d.scrollWidth>d.clientWidth+1,product:document.querySelector('#rfq-product')?.value,quantity:document.querySelector('#rfq-quantity')?.value}});const mailtoPass=filled.href.startsWith('mailto:sales@uniqueholding.com.tr?subject=')&&filled.href.includes('body=')&&decodeURIComponent(filled.href).includes('Urea 46')&&!filled.overflow;await p.click('#rfq-reset');await sleep(80);const reset=await p.evaluate(()=>({values:[...document.querySelectorAll('#rfq-builder input,#rfq-builder textarea')].map(e=>e.value),href:document.querySelector('#rfq-email-action')?.getAttribute('href')||''}));out.push({name:'rfq-labels-filled-mailto-long-reset',pass:labels.count>=10&&!labels.unlabelled.length&&mailtoPass&&reset.values.every(v=>v==='')&&reset.href.startsWith('mailto:sales@uniqueholding.com.tr'),labels,filled:{hrefPrefix:filled.href.slice(0,180),overflow:filled.overflow,product:filled.product,quantityLength:filled.quantity.length},reset:{allCleared:reset.values.every(v=>v===''),href:reset.href}});await p.close();
 p=await pageFor(browser,390,844);await p.goto(BASE+'privacy.html',{waitUntil:'load'});out.push({name:'external-link-keyboard-focus',...(await focusVisible(p,'a[href="https://evidenceaxis.com/contact/"]'))});await p.close();
 p=await pageFor(browser,390,844);const filmErrors=[];p.on('pageerror',e=>filmErrors.push(String(e)));await p.goto(BASE+'index.html',{waitUntil:'domcontentloaded'});await sleep(1000);const film=await p.evaluate(()=>{const box=document.querySelector('.hero-film-controls'),video=document.querySelector('video'),buttons=box?[...box.querySelectorAll('button')]:[];return {controls:!!box,video:!!video,buttonCount:buttons.length,visibleButtons:buttons.filter(b=>{const s=getComputedStyle(b),r=b.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0}).length,labels:buttons.map(b=>b.getAttribute('aria-label')||b.textContent.trim()).filter(Boolean)};});out.push({name:'protected-film-controls',pass:film.controls&&film.video&&film.buttonCount>0&&film.visibleButtons>0&&!filmErrors.length,film,errors:filmErrors});await p.close();
 return out;
}
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const report={spotcheck:[],smoke:[],interactions:[],summary:{}};try{for(const x of spots)report.spotcheck.push(await load(browser,x.route,x.w,x.h,true));for(const r of routes)for(const [w,h] of [[1440,900],[390,844]])report.smoke.push(await load(browser,r,w,h,false));report.interactions=await interactions(browser)}finally{await browser.close()}const spotFailures=report.spotcheck.filter(x=>!valid(x)),smokeFailures=report.smoke.filter(x=>!valid(x)),interactionFailures=report.interactions.filter(x=>!x.pass);const externalFailureEvents=[...report.spotcheck,...report.smoke].reduce((n,x)=>n+x.externalFailures.length,0);report.summary={spotcheckCount:report.spotcheck.length,spotcheckFailures:spotFailures.length,screenshotCount:fs.readdirSync(SHOTS).filter(x=>x.endsWith('.png')).length,smokeCases:report.smoke.length,smokeFailures:smokeFailures.length,interactionCases:report.interactions.length,interactionFailures:interactionFailures.length,externalFailureEvents};fs.writeFileSync(path.join(OUT,'phase21-spotcheck.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary,null,2));if(spotFailures.length||smokeFailures.length||interactionFailures.length)process.exitCode=2})().catch(e=>{console.error(e);process.exit(1)});
