const fs=require('fs'),path=require('path'),puppeteer=require('puppeteer-core');
const BASE=process.env.PHASE20_BASE||'http://127.0.0.1:8000/';
const OUT=process.env.PHASE20_OUT||'/tmp/phase20-visual';
const shotsDir=path.join(OUT,'screenshots');fs.mkdirSync(shotsDir,{recursive:true});
const routes=['index.html','corporate.html','energy.html','products.html','product.html','urea-46.html','caustic-soda-solid.html','sodium-sulphate-anhydrous.html','sales.html','technology.html','evidence-axis.html','ventures.html','contact.html','privacy.html','legal.html','404.html'];
const views=[[1920,1080],[1440,900],[768,1024],[390,844],[360,800]];
const matrix=[];
const add=(route,vs)=>vs.forEach(([w,h])=>matrix.push({route,w,h}));
add('index.html',views);add('energy.html',views);add('products.html',views);add('sales.html',views);add('technology.html',views);add('contact.html',views);
add('corporate.html',views);
add('evidence-axis.html',[[390,844],[360,800]]);add('ventures.html',[[390,844],[360,800]]);
for(const r of ['urea-46.html','caustic-soda-solid.html','sodium-sulphate-anhydrous.html'])add(r,[[1440,900],[390,844]]);
for(const r of ['privacy.html','legal.html'])add(r,[[1440,900],[390,844],[360,800]]);
add('404.html',[[1440,900],[390,844]]);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const safe=s=>s.replace(/\.html$/,'').replace(/[^a-z0-9-]/gi,'_');
async function newPage(browser,w,h){const p=await browser.newPage();await p.setViewport({width:w,height:h,deviceScaleFactor:1});await p.setCacheEnabled(false);return p}
async function inspectPage(page){return await page.evaluate(()=>{
 const de=document.documentElement,b=document.body,main=document.querySelector('main'),h1=main?.querySelectorAll('h1').length||0,footer=document.querySelector('.site-footer, footer');
 const vis=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0};
 const header=document.querySelector('[data-header],header'); const nav=document.querySelector('.primary-nav');
 const edges=[...document.querySelectorAll('main *')].filter(vis).filter(e=>{const r=e.getBoundingClientRect();return r.left<-1||r.right>innerWidth+1}).slice(0,20).map(e=>({tag:e.tagName,cls:e.className?.toString().slice(0,100)||'',text:(e.textContent||'').trim().slice(0,100),left:Math.round(e.getBoundingClientRect().left),right:Math.round(e.getBoundingClientRect().right)}));
 const fixed=[...document.querySelectorAll('header,nav,button,a')].filter(vis).map(e=>{const r=e.getBoundingClientRect();return {tag:e.tagName,cls:e.className?.toString().slice(0,80)||'',text:(e.getAttribute('aria-label')||e.textContent||'').trim().slice(0,60),x:Math.round(r.x),y:Math.round(r.y),w:Math.round(r.width),h:Math.round(r.height)}}).filter(x=>x.y<180).slice(0,30);
 return {title:document.title,scrollWidth:de.scrollWidth,clientWidth:de.clientWidth,overflow:de.scrollWidth>de.clientWidth+1,main:!!main,h1,footer:!!footer,bodyHeight:Math.round(b.scrollHeight),edgeOffenders:edges,headerNav:fixed,active:document.activeElement?.tagName||''};
})}
async function crawlLinks(page){return await page.evaluate(async()=>{
 const here=new URL(location.href);const hrefs=[...new Set([...document.querySelectorAll('a[href]')].map(a=>a.getAttribute('href')).filter(Boolean).filter(h=>!h.startsWith('#')&&!h.startsWith('mailto:')&&!h.startsWith('tel:')&&!h.startsWith('javascript:')).map(h=>new URL(h,location.href).href).filter(u=>new URL(u).origin===here.origin))];
 const out=[];for(const u of hrefs){try{const r=await fetch(u,{cache:'no-store'});out.push({url:u,status:r.status,ok:r.ok})}catch(e){out.push({url:u,status:0,ok:false,error:String(e)})}}return out;
})}
async function capture(browser,item){const p=await newPage(browser,item.w,item.h);const errors=[];p.on('console',m=>{if(m.type()==='error')errors.push('console:'+m.text())});p.on('pageerror',e=>errors.push('page:'+String(e)));p.on('requestfailed',r=>errors.push('request:'+r.url()+':'+(r.failure()?.errorText||'')));let status=0;try{const resp=await p.goto(BASE+item.route,{waitUntil:'networkidle2',timeout:45000});status=resp?.status()||0}catch(e){errors.push('nav:'+String(e))}await sleep(item.route==='index.html'?2200:700);const visual=await inspectPage(p);const file=`${safe(item.route)}-${item.w}x${item.h}.png`;await p.screenshot({path:path.join(shotsDir,file),fullPage:true});await p.close();return {...item,status,errors,visual,file}}
async function smoke(browser,route,w,h){const p=await newPage(browser,w,h);const errors=[];p.on('pageerror',e=>errors.push(String(e)));p.on('requestfailed',r=>errors.push('request:'+r.url()+':'+(r.failure()?.errorText||'')));let status=0;try{const resp=await p.goto(BASE+route,{waitUntil:'load',timeout:45000});status=resp?.status()||0}catch(e){errors.push('nav:'+String(e))}await sleep(250);const visual=await inspectPage(p);const links=await crawlLinks(p);await p.close();return {route,w,h,status,errors,visual,brokenInternalLinks:links.filter(x=>!x.ok)}}
async function interactions(browser){const out=[];
 // desktop navigation visible state
 let p=await newPage(browser,1440,900);await p.goto(BASE+'index.html',{waitUntil:'load'});await sleep(500);await p.screenshot({path:path.join(shotsDir,'interaction-desktop-nav-1440x900.png')});out.push({name:'desktop-nav',pass:await p.evaluate(()=>{const n=document.querySelector('.primary-nav');return !!n&&getComputedStyle(n).display!=='none'})});await p.close();
 // mobile menu open, escape and focus restoration
 p=await newPage(browser,390,844);await p.goto(BASE+'index.html',{waitUntil:'load'});await sleep(400);const menu=await p.$('.menu-toggle');if(menu){await menu.click();await sleep(250);await p.screenshot({path:path.join(shotsDir,'interaction-mobile-nav-open-390x844.png')});const open=await p.evaluate(()=>({open:document.querySelector('.primary-nav')?.classList.contains('is-open'),expanded:document.querySelector('.menu-toggle')?.getAttribute('aria-expanded'),focus:(document.activeElement?.textContent||'').trim().slice(0,40)}));await p.keyboard.press('Escape');await sleep(150);const closed=await p.evaluate(()=>({open:document.querySelector('.primary-nav')?.classList.contains('is-open'),expanded:document.querySelector('.menu-toggle')?.getAttribute('aria-expanded'),restored:document.activeElement===document.querySelector('.menu-toggle')}));out.push({name:'mobile-menu',pass:open.open&&open.expanded==='true'&&!closed.open&&closed.expanded==='false'&&closed.restored,open,closed})}else out.push({name:'mobile-menu',pass:false,reason:'menu toggle missing'});await p.close();
 // skip link visible on focus
 p=await newPage(browser,390,844);await p.goto(BASE+'corporate.html',{waitUntil:'load'});await p.keyboard.press('Tab');await sleep(100);await p.screenshot({path:path.join(shotsDir,'interaction-skip-link-focus-390x844.png')});out.push({name:'skip-link',pass:await p.evaluate(()=>document.activeElement?.classList.contains('skip-link')&&getComputedStyle(document.activeElement).visibility!=='hidden')});await p.close();
 // CTA focus state
 p=await newPage(browser,1440,900);await p.goto(BASE+'contact.html',{waitUntil:'load'});await p.evaluate(()=>{const e=document.querySelector('main a[href],main button');e?.focus();e?.scrollIntoView({block:'center'})});await sleep(120);await p.screenshot({path:path.join(shotsDir,'interaction-contact-cta-focus-1440x900.png')});out.push({name:'cta-focus',pass:await p.evaluate(()=>document.activeElement&&document.activeElement!==document.body)});await p.close();
 // RFQ form filled / long input state
 p=await newPage(browser,390,844);await p.goto(BASE+'contact.html',{waitUntil:'load'});await sleep(300);const inputs=await p.$$('main input,main textarea,main select');if(inputs.length){for(const e of inputs){const tag=await e.evaluate(x=>x.tagName);const type=await e.evaluate(x=>x.type||'');if(tag==='SELECT'){const opts=await e.$$eval('option',os=>os.map(o=>o.value).filter(Boolean));if(opts[0])await e.select(opts[0]);}else if(type!=='submit'&&type!=='reset'&&type!=='button'){await e.focus();await e.type('Phase 20 visual QC long input sample for wrapping and control layout — Istanbul industrial inquiry 1234567890',{delay:0});}}await p.evaluate(()=>document.querySelector('form')?.scrollIntoView({block:'start'}));await sleep(150);await p.screenshot({path:path.join(shotsDir,'interaction-rfq-filled-390x844.png'),fullPage:false});}out.push({name:'rfq-visual',pass:inputs.length>0});await p.close();
 // external link focus treatment on legal
 p=await newPage(browser,390,844);await p.goto(BASE+'legal.html',{waitUntil:'load'});const ext=await p.$('a[target="_blank"],a[href^="http"]');if(ext){await ext.focus();await ext.evaluate(e=>e.scrollIntoView({block:'center'}));await sleep(100);await p.screenshot({path:path.join(shotsDir,'interaction-external-link-focus-390x844.png')});out.push({name:'external-link-focus',pass:true})}else out.push({name:'external-link-focus',pass:true,observation:'no explicit external link on route'});await p.close();
 // protected film controls visual state only
 p=await newPage(browser,390,844);await p.goto(BASE+'index.html',{waitUntil:'domcontentloaded'});await sleep(1800);await p.screenshot({path:path.join(shotsDir,'interaction-film-controls-390x844.png')});out.push({name:'film-controls-visible',pass:await p.evaluate(()=>!!document.querySelector('.hero-film-controls'))});await p.close();
 return out;
}
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const report={matrix:[],smoke:[],interactions:[],summary:{}};try{for(const item of matrix)report.matrix.push(await capture(browser,item));for(const route of routes)for(const [w,h] of [[1440,900],[390,844]])report.smoke.push(await smoke(browser,route,w,h));report.interactions=await interactions(browser);}finally{await browser.close()}
 report.summary={matrixCount:report.matrix.length,matrixFailures:report.matrix.filter(x=>x.status!==200||x.errors.length||x.visual.overflow||!x.visual.main||x.visual.h1!==1||!x.visual.footer).length,smokeCases:report.smoke.length,smokeFailures:report.smoke.filter(x=>x.status!==200||x.errors.length||x.visual.overflow||!x.visual.main||x.visual.h1!==1||!x.visual.footer||x.brokenInternalLinks.length).length,interactionCases:report.interactions.length,interactionFailures:report.interactions.filter(x=>!x.pass).length,screenshotCount:fs.readdirSync(shotsDir).filter(x=>x.endsWith('.png')).length};
 fs.writeFileSync(path.join(OUT,'phase20-visual.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary,null,2));if(report.summary.matrixFailures||report.summary.smokeFailures||report.summary.interactionFailures)process.exitCode=2;
})();