const fs=require('fs'),path=require('path'),puppeteer=require('puppeteer-core');
const BASE='http://127.0.0.1:8000/';
const OUT=process.env.PHASE18_BROWSER_OUT||'/tmp/phase18-browser';
const routes=['index.html','corporate.html','energy.html','products.html','product.html','urea-46.html','caustic-soda-solid.html','sodium-sulphate-anhydrous.html','sales.html','technology.html','evidence-axis.html','ventures.html','contact.html','privacy.html','legal.html','404.html'];
const smokeViewports=[[1440,900],[390,844]];
const repRoutes=['index.html','products.html','technology.html','evidence-axis.html','contact.html'];
const repViewports=[[1920,1080],[1440,900],[768,1024],[390,844],[360,800]];
const social=['group-corporate.png','industrial-trade.png','technology-intelligence.png','evidence-axis.png','venture-portfolio.png'];
const report={smoke:[],representative:[],coreProducts:[],legal:[],robotsSitemap:null,socialCards:[],failures:[],summary:{}};
for(const d of ['screenshots/representative','screenshots/core-products','screenshots/legal','screenshots/social-native','screenshots/social-reduced','reports'])fs.mkdirSync(path.join(OUT,d),{recursive:true});
const fail=(scope,msg,data={})=>report.failures.push({scope,msg,...data});
const ok=(c,s,m,d={})=>{if(!c)fail(s,m,d)};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function newPage(browser,w,h){const ctx=await browser.createBrowserContext();const page=await ctx.newPage();await page.setViewport({width:w,height:h,deviceScaleFactor:1});const e={console:[],page:[],failed:[]};page.on('console',m=>{if(m.type()==='error')e.console.push(m.text())});page.on('pageerror',x=>e.page.push(String(x)));page.on('requestfailed',r=>e.failed.push({url:r.url(),type:r.resourceType(),error:r.failure()?.errorText||''}));return{ctx,page,e}}
async function go(page,route,wait=650){const r=await page.goto(route.startsWith('http')?route:BASE+route,{waitUntil:'domcontentloaded',timeout:30000});await sleep(wait);return{status:r?.status()||0,url:page.url()}}
async function shell(page,w){return page.evaluate(width=>{const ids=[...document.querySelectorAll('[id]')].map(x=>x.id);return{main:!!document.querySelector('main'),header:!!document.querySelector('.site-header'),footer:!!document.querySelector('.site-footer'),h1:document.querySelectorAll('main h1').length,sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,overflow:document.documentElement.scrollWidth>width+1,dupIds:[...new Set(ids.filter((x,i)=>ids.indexOf(x)!==i))]};},w)}
async function capture(page,file){await page.screenshot({path:file,type:'jpeg',quality:78,fullPage:true})}
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});try{
  // 32 site-wide browser smoke cases.
  for(const route of routes)for(const [w,h] of smokeViewports){const scope=`smoke:${route}:${w}x${h}`;const{ctx,page,e}=await newPage(browser,w,h);let nav={status:0,url:''};try{nav=await go(page,route)}catch(err){fail(scope,'navigation error',{error:String(err)})}const s=await shell(page,w);ok([200,304].includes(nav.status),scope,'local route response failed',{nav});ok(s.main&&s.header&&s.footer,scope,'header/main/footer missing',s);ok(s.h1===1,scope,'expected exactly one main H1',s);ok(!s.overflow,scope,'horizontal overflow',s);ok(s.dupIds.length===0,scope,'duplicate IDs',s);ok(e.console.length===0&&e.page.length===0&&e.failed.length===0,scope,'browser/request errors',{e});report.smoke.push({route,w,h,status:nav.status,shell:s,browserErrors:{console:e.console.length,page:e.page.length,failed:e.failed.length},pass:!report.failures.some(f=>f.scope===scope)});await ctx.close()}

  // 25 representative five-viewport visual cases.
  for(const route of repRoutes)for(const [w,h] of repViewports){const scope=`representative:${route}:${w}x${h}`;const{ctx,page,e}=await newPage(browser,w,h);const nav=await go(page,route);const s=await shell(page,w);ok([200,304].includes(nav.status),scope,'route response failed',{nav});ok(s.main&&s.header&&s.footer&&s.h1===1&&!s.overflow,scope,'representative layout regression',s);ok(e.console.length===0&&e.page.length===0&&e.failed.length===0,scope,'representative browser errors',{e});const file=path.join(OUT,'screenshots/representative',`${route.replace('.html','')}-${w}x${h}.jpg`);await capture(page,file);report.representative.push({route,w,h,file:path.relative(OUT,file),pass:!report.failures.some(f=>f.scope===scope)});await ctx.close()}

  // Core Product mobile regression, exact published values and reference status.
  const coreExpected={
    'urea-46.html':[['Nitrogen Content','min 46% wt'],['Biuret','max 0.8% wt'],['Formaldehyde','max 0.55% wt'],['Moisture','max 0.3% wt'],['Particle size 2–4 mm','90%']],
    'caustic-soda-solid.html':[['Chemical name','Sodium Hydroxide'],['CAS','1310-73-2'],['NaOH','approx. 98.8%'],['Dry basis','99.3%'],['UN number','1823'],['Class','8'],['Packing Group','II']],
    'sodium-sulphate-anhydrous.html':[['Na₂SO₄','99.20%'],['Water Insoluble Matter','0.02%'],['Ca & Mg','0.02%'],['Chloride','0.30%'],['Fe','0.0003%'],['Moisture','0.05%'],['Whiteness','91%']]
  };
  for(const [route,pairs] of Object.entries(coreExpected)){const scope=`core:${route}:390x844`;const{ctx,page,e}=await newPage(browser,390,844);await go(page,route);const d=await page.evaluate(()=>({reference:document.querySelector('[data-reference-detail="true"]')!==null,status:document.querySelector('.reference-status')?.textContent.trim()||'',text:document.body.innerText,overflow:document.documentElement.scrollWidth>391,rfq:[...document.querySelectorAll('a[href*="sales.html"]')].length}));ok(d.reference&&/reference detail/i.test(d.status),scope,'Reference Detail status regression',d);ok(!d.overflow,scope,'core product horizontal overflow',d);ok(d.rfq>0,scope,'core product sales routing missing',d);for(const [name,value] of pairs){ok(d.text.includes(name)&&d.text.includes(value),scope,'published technical value changed/missing',{name,value})}ok(e.console.length===0&&e.page.length===0&&e.failed.length===0,scope,'core product browser errors',{e});const file=path.join(OUT,'screenshots/core-products',`${route.replace('.html','')}-390x844.jpg`);await capture(page,file);report.coreProducts.push({route,w:390,h:844,file:path.relative(OUT,file),pass:!report.failures.some(f=>f.scope===scope)});await ctx.close()}

  // Phase 17 Privacy / Legal mobile regression.
  for(const route of ['privacy.html','legal.html']){const scope=`legal:${route}:390x844`;const{ctx,page,e}=await newPage(browser,390,844);await go(page,route);const d=await page.evaluate(()=>{const bodySel='.legal-hero .intro,.legal-policy-section .section-cap > p,.legal-card p,.legal-split p,.legal-callout p,.legal-review-grid p,.legal-contact-panel p';const isLastUpdated=e=>{const cell=e.closest('#legal-contact .legal-contact-panel > div');const label=cell?.querySelector('.legal-label')?.textContent.trim().toUpperCase()||'';return label==='LAST UPDATED'};const body=[...document.querySelectorAll(bodySel)].filter(e=>e.textContent.trim()&&!isLastUpdated(e)).map(e=>({text:e.textContent.trim().slice(0,80),size:parseFloat(getComputedStyle(e).fontSize)}));const actions=[...new Set([...document.querySelectorAll('main .button-link'),...document.querySelectorAll('main .legal-link-row a'),...document.querySelectorAll('main .legal-contact-panel a')])].map(a=>{const r=a.getBoundingClientRect();return{text:a.textContent.trim(),x:r.x,right:r.right,height:r.height}});return{minBody:Math.min(...body.map(x=>x.size)),actions,overflow:document.documentElement.scrollWidth>391,text:document.body.innerText}});ok(d.minBody+0.01>=16,scope,'Phase 17 semantic body font below 16px',{minBody:d.minBody});ok(!d.overflow,scope,'Phase 17 horizontal overflow',d);for(const a of d.actions)ok(a.x>=-1&&a.right<=391&&a.height>=40,scope,'Phase 17 mobile action not touch-safe',{a});ok(/legal review required/i.test(d.text),scope,'Phase 17 legal-review boundary missing');ok(e.console.length===0&&e.page.length===0&&e.failed.length===0,scope,'Phase 17 browser errors',{e});const file=path.join(OUT,'screenshots/legal',`${route.replace('.html','')}-390x844.jpg`);await capture(page,file);report.legal.push({route,w:390,h:844,minBody:d.minBody,file:path.relative(OUT,file),pass:!report.failures.some(f=>f.scope===scope)});await ctx.close()}

  // robots.txt / sitemap.xml served locally.
  {const{ctx,page}=await newPage(browser,1200,800);const robotsResp=await page.goto(BASE+'robots.txt',{waitUntil:'domcontentloaded'});const robotsText=await page.evaluate(()=>document.body.innerText);const sitemapResp=await page.goto(BASE+'sitemap.xml',{waitUntil:'domcontentloaded'});const sitemapText=await page.evaluate(()=>document.body.innerText);const urls=[...sitemapText.matchAll(/https:\/\/www\.uniqueholding\.com\.tr\/(?:[A-Za-z0-9_.-]+\.html)?/g)].map(m=>m[0]);const expected=['https://www.uniqueholding.com.tr/','https://www.uniqueholding.com.tr/corporate.html','https://www.uniqueholding.com.tr/energy.html','https://www.uniqueholding.com.tr/products.html','https://www.uniqueholding.com.tr/urea-46.html','https://www.uniqueholding.com.tr/caustic-soda-solid.html','https://www.uniqueholding.com.tr/sodium-sulphate-anhydrous.html','https://www.uniqueholding.com.tr/sales.html','https://www.uniqueholding.com.tr/technology.html','https://www.uniqueholding.com.tr/evidence-axis.html','https://www.uniqueholding.com.tr/ventures.html','https://www.uniqueholding.com.tr/contact.html','https://www.uniqueholding.com.tr/privacy.html','https://www.uniqueholding.com.tr/legal.html'];ok(robotsResp?.status()===200,'robots-sitemap','robots response missing',{status:robotsResp?.status()});ok(sitemapResp?.status()===200,'robots-sitemap','sitemap response missing',{status:sitemapResp?.status()});ok(robotsText.includes('Sitemap: https://www.uniqueholding.com.tr/sitemap.xml'),'robots-sitemap','robots sitemap declaration mismatch',{robotsText});ok(urls.length===14&&JSON.stringify(urls)===JSON.stringify(expected),'robots-sitemap','served sitemap canonical set mismatch',{urls});ok(!urls.some(u=>u.includes('product.html')||u.includes('404.html')||u.includes('?')),'robots-sitemap','served sitemap includes forbidden route',{urls});report.robotsSitemap={robotsStatus:robotsResp?.status(),sitemapStatus:sitemapResp?.status(),urls,count:urls.length,pass:!report.failures.some(f=>f.scope==='robots-sitemap')};await ctx.close()}

  // Direct social-card browser checks at native and reduced preview sizes.
  for(const file of social){for(const [label,w,h] of [['native',1200,630],['reduced',600,315]]){const scope=`social:${file}:${label}`;const{ctx,page,e}=await newPage(browser,w,h);const nav=await go(page,BASE+'assets/social/'+file,120);const d=await page.evaluate(()=>{const img=document.querySelector('img');if(!img)return null;const r=img.getBoundingClientRect();return{naturalWidth:img.naturalWidth,naturalHeight:img.naturalHeight,width:r.width,height:r.height,x:r.x,y:r.y}});ok(nav.status===200,scope,'social image response failed',{nav});ok(d&&d.naturalWidth===1200&&d.naturalHeight===630,scope,'social image intrinsic dimensions mismatch',{d});ok(e.console.length===0&&e.page.length===0&&e.failed.length===0,scope,'social image browser errors',{e});const dir=label==='native'?'screenshots/social-native':'screenshots/social-reduced';const out=path.join(OUT,dir,file.replace('.png','.jpg'));await page.screenshot({path:out,type:'jpeg',quality:86});report.socialCards.push({file,scale:label,w,h,natural:d,fileOut:path.relative(OUT,out),pass:!report.failures.some(f=>f.scope===scope)});await ctx.close()}}
}finally{await browser.close()}
report.summary={smokeCases:report.smoke.length,smokeFailures:report.smoke.filter(x=>!x.pass).length,representativeCases:report.representative.length,representativeFailures:report.representative.filter(x=>!x.pass).length,coreProductCases:report.coreProducts.length,coreProductFailures:report.coreProducts.filter(x=>!x.pass).length,privacyLegalCases:report.legal.length,privacyLegalFailures:report.legal.filter(x=>!x.pass).length,socialCardCases:report.socialCards.length,socialCardFailures:report.socialCards.filter(x=>!x.pass).length,robotsSitemapPass:!!report.robotsSitemap?.pass,totalFailures:report.failures.length};
fs.writeFileSync(path.join(OUT,'reports/phase18-browser-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report.summary,null,2));if(report.failures.length){console.error(JSON.stringify(report.failures,null,2));process.exit(1)}console.log('PHASE 18 BROWSER QA PASS');})();
