const fs=require('fs');
const BASE='83567c124d171bf5d3664b41d8547555a2d196a8';
const read=p=>fs.readFileSync(p,'utf8');
const write=(p,s)=>fs.writeFileSync(p,s);
const must=(text,needle,label)=>{if(!text.includes(needle))throw new Error('Missing '+label)};
const replace=(text,needle,value,label)=>{must(text,needle,label);return text.replace(needle,value)};

let products=read('products.html');
let product=read('product.html');
let qa=read('scripts/qa-site.mjs');

products=replace(products,
  '<link rel="stylesheet" href="assets/internal.css"><style>@layer page{html{scroll-behavior:auto}.catalog-anchor{scroll-margin-top:96px}}</style>',
  '<link rel="stylesheet" href="assets/internal.css"><link rel="stylesheet" href="assets/products-ia.css">',
  'products IA stylesheet hook');

const oldHero='<section class="subsite-hero energy"><div class="inner"><p class="subsite-label">Energy &amp; Global Trade / Products</p><h1>Industrial<br>Products.</h1><p class="intro">Core products with published reference technical data are separated from the wider inquiry catalog. Availability, origin, producer and final specification are confirmed only during commercial review of the offered lot.</p><a class="back" href="energy.html">Back to Energy ↗</a></div></section>';
const newHero='<section class="subsite-hero energy products-hero"><div class="inner"><p class="subsite-label">Energy &amp; Global Trade / Products</p><h1>Industrial<br>Products.</h1><p class="intro">Three core industrial products carry published reference technical information. The wider catalog is organized as commercial inquiry families, reviewed against each requirement and offered lot.</p><div class="products-hero-actions"><a href="#core-products">Core products ↓</a><a href="#inquiry-families">Inquiry families ↓</a></div><a class="back" href="energy.html">Back to Energy ↗</a></div></section>';
products=replace(products,oldHero,newHero,'products hero');

products=replace(products,
  newHero+'\n<section class="subsite-section" id="core-products">',
  newHero+'\n<nav class="product-ia-path" aria-label="Product information architecture"><ol><li><a href="#core-products"><small>Level 1</small><strong>Core Industrial Products</strong><span>Published reference technical information</span></a></li><li><a href="#inquiry-families"><small>Level 2</small><strong>Product Families</strong><span>Commercial inquiry categories</span></a></li><li><a href="#petrochemical"><small>Level 3</small><strong>Product Inquiry Routes</strong><span>Individual product requirements</span></a></li><li><a href="#industrial-sales"><small>Level 4</small><strong>Industrial Sales / RFQ</strong><span>Commercial review and next steps</span></a></li></ol></nav>\n<section class="subsite-section" id="core-products" data-ia-level="1">',
  'IA path insertion');

products=replace(products,
  '<div class="section-cap"><span class="num">01 / Core Products</span><h2>Products with published reference technical data.</h2><p>These materials have product-level reference specifications available on the site. Final specification, packing and commercial terms remain subject to the offered lot and confirmation at the time of inquiry.</p></div><div class="product-grid" id="core-grid">',
  '<div class="section-cap product-section-cap"><span class="num">01 / Core Industrial Products</span><h2>Published reference technical information.</h2><p>Three primary industrial products have dedicated reference-detail pages. Reference values support initial review; final specification, packing and commercial terms remain subject to the offered lot and confirmation at inquiry.</p></div><div class="core-distinction" role="note"><span>Reference route</span><p>These three products have published technical-reference pages. They are distinct from the wider commercial inquiry catalog below.</p></div><div class="product-grid" id="core-grid">',
  'core section hierarchy');

products=products.replace(/<a class="product-link" data-product-kind="core"/g,'<a class="product-link" data-product-kind="core" data-destination="reference-detail"');
products=products.replace(/<a class="product-link" data-product-kind="inquiry"/g,'<a class="product-link" data-product-kind="inquiry" data-destination="inquiry-detail" data-ia-level="3"');
products=replace(products,'data-slug="urea-46" href="product.html?slug=urea-46"','data-slug="urea-46" href="urea-46.html"','Urea reference route');
products=replace(products,'data-slug="caustic-soda-solid" href="product.html?slug=caustic-soda-solid"','data-slug="caustic-soda-solid" href="caustic-soda-solid.html"','Caustic reference route');
products=replace(products,'data-slug="sodium-sulphate-anhydrous" href="product.html?slug=sodium-sulphate-anhydrous"','data-slug="sodium-sulphate-anhydrous" href="sodium-sulphate-anhydrous.html"','Sodium sulphate reference route');
products=products.replaceAll('Reference technical data ↗','Published reference detail ↗');
products=products.replaceAll('Open inquiry route ↗','Inquiry detail ↗');

products=replace(products,
  '<section class="subsite-section alt" id="inquiry-families"><div class="section-cap"><span class="num">02 / Additional Inquiry Families</span><h2>Broader petrochemical and industrial-material routes.</h2><p>The families below are maintained as commercial inquiry routes, not as a claim of stocked inventory or guaranteed availability. Product, grade, specification, quantity, destination and timing are reviewed per inquiry.</p></div><div class="catalog-tools"><input class="catalog-search" id="product-search" type="search" placeholder="Search MEG, HDPE, Urea, Bitumen…" aria-label="Search additional product inquiry families"><span class="catalog-count" id="product-count"></span></div><div id="catalog">',
  '<section class="subsite-section alt" id="inquiry-families" data-ia-level="2"><div class="section-cap product-section-cap"><span class="num">02 / Product Families &amp; Inquiry Categories</span><h2>A structured commercial inquiry index.</h2><p>The 62 routes below are inquiry pathways, not standing claims of stock, producer ownership, fixed origin or guaranteed availability. Product, grade, specification, quantity, destination and timing are reviewed per requirement.</p></div><div class="catalog-scope" id="catalog-scope"><strong>Catalog distinction</strong><span>Core reference pages publish selected technical reference information.</span><span>Inquiry routes identify commercial product families for requirement-by-requirement review.</span></div><nav class="product-family-nav" aria-label="Inquiry category navigation"><a href="#petrochemical"><small>Category 01</small><strong>Petrochemical Products</strong><span>Polymers · olefins · aromatics · glycols · intermediates · fertilizers</span></a><a href="#chemical"><small>Category 02</small><strong>Chemical Products</strong><span>Industrial chemical inquiry families</span></a><a href="#energy-products"><small>Category 03</small><strong>Energy &amp; Hydrocarbon Products</strong><span>Liquefied gases · refinery materials · hydrocarbon streams</span></a></nav><div class="catalog-tools"><label for="product-search"><span>Search inquiry routes</span><input class="catalog-search" id="product-search" type="search" placeholder="Search MEG, HDPE, Urea, Bitumen…" aria-label="Search additional product inquiry families" aria-controls="catalog" aria-describedby="catalog-scope"></label><div class="catalog-status"><span class="catalog-count" id="product-count" aria-live="polite"></span><button class="catalog-clear" id="product-search-clear" type="button">Clear</button></div></div><p class="catalog-empty" id="catalog-empty" hidden>No inquiry routes match this search.</p><div id="catalog">',
  'inquiry architecture');

products=replace(products,
  '</main>',
  '<section class="subsite-section product-rfq" id="industrial-sales" data-ia-level="4"><div class="product-rfq-grid"><div><span class="num">04 / Industrial Sales / RFQ</span><h2>Move from product route to commercial review.</h2></div><div><p>For a commercial review, provide the product, grade or target specification, quantity, destination and timing. Producer, origin, packing, availability and final terms are confirmed only when relevant to the offered lot and transaction.</p><a class="button-link primary" href="sales.html">Open Industrial Sales / RFQ guide</a></div></div></section>\n</main>',
  'RFQ architecture section');

const newSearch='<script src="assets/products-data.js"></script><script>(function(){const catalog=document.getElementById(\'catalog\');const input=document.getElementById(\'product-search\');const count=document.getElementById(\'product-count\');const clear=document.getElementById(\'product-search-clear\');const empty=document.getElementById(\'catalog-empty\');const cards=[...catalog.querySelectorAll(\'[data-product-kind="inquiry"]\')];const families=[...catalog.querySelectorAll(\'[data-catalog-family]\')];const groups=[...catalog.querySelectorAll(\'[data-catalog-category]\')];function filter(q=\'\'){const term=q.trim().toLowerCase();let visible=0;for(const card of cards){const match=!term||(card.dataset.search||card.textContent.toLowerCase()).includes(term);card.hidden=!match;if(match)visible++;}for(const family of families)family.hidden=!family.querySelector(\'[data-product-kind="inquiry"]:not([hidden])\');for(const group of groups)group.hidden=!group.querySelector(\'[data-catalog-family]:not([hidden])\');count.textContent=visible+\' inquiry routes\';empty.hidden=visible!==0;clear.disabled=!term;}input.addEventListener(\'input\',e=>filter(e.target.value));input.addEventListener(\'search\',e=>filter(e.target.value));clear.addEventListener(\'click\',()=>{input.value=\'\';filter();input.focus();});filter(input.value);})();</script>';
if(!/<script src="assets\/products-data\.js"><\/script><script>\(function\(\)\{[\s\S]*?\}\)\(\);<\/script>/.test(products))throw new Error('Search script pattern missing');
products=products.replace(/<script src="assets\/products-data\.js"><\/script><script>\(function\(\)\{[\s\S]*?\}\)\(\);<\/script>/,newSearch);

product=replace(product,'<link rel="stylesheet" href="assets/internal.css"></head>','<link rel="stylesheet" href="assets/internal.css"><link rel="stylesheet" href="assets/products-ia.css"></head>','product IA stylesheet hook');
product=replace(product,
  '<main id="main"><div class="detail-shell"><a class="detail-back" href="products.html">← Back to product catalog</a><p class="subsite-label" id="product-family">Industrial Product</p>',
  '<main id="main"><div class="detail-shell"><nav class="detail-breadcrumb" aria-label="Breadcrumb"><a href="index.html">Unique Holding</a><span aria-hidden="true">/</span><a href="products.html">Industrial Products</a><span aria-hidden="true">/</span><span id="product-breadcrumb" aria-current="page">Inquiry detail</span></nav><div class="product-route-context" aria-label="Product information path"><div><small>Level 2</small><span id="route-family">Product family</span></div><i aria-hidden="true">→</i><div><small>Level 3</small><span id="route-product">Inquiry detail</span></div><i aria-hidden="true">→</i><a href="sales.html"><small>Level 4</small><span>Industrial Sales / RFQ</span></a></div><p class="subsite-label" id="product-family">Industrial Product</p>',
  'product inquiry breadcrumb');

const productScript=`<script src="assets/products-data.js"></script><script>(function(){const slug=new URLSearchParams(location.search).get('slug');const coreRoutes={'urea-46':'urea-46.html','caustic-soda-solid':'caustic-soda-solid.html','sodium-sulphate-anhydrous':'sodium-sulphate-anhydrous.html'};if(coreRoutes[slug]){location.replace(coreRoutes[slug]);return;}const all=window.UNIQUE_PRODUCTS||[];const p=all.find(x=>x.slug===slug);if(!p){document.getElementById('product-name').textContent='Product not found';document.getElementById('product-summary').textContent='Return to the product catalog to select an available inquiry route.';document.getElementById('product-breadcrumb').textContent='Route not found';return;}document.body.dataset.productRoute='inquiry-detail';document.title=p.name+' | Unique Holding';document.getElementById('product-breadcrumb').textContent=p.name;document.getElementById('route-family').textContent=p.family;document.getElementById('route-product').textContent=p.name;document.getElementById('product-family').textContent=p.family;document.getElementById('product-name').textContent=p.name;document.getElementById('product-abbr').textContent=p.abbr||p.category;document.getElementById('product-summary').textContent='Commercial inquiry route for '+p.name+'. Availability, grade, specification, packing and commercial terms are reviewed against the requested requirement and offered lot.';let classification=p.category+' · '+p.family;if(p.variants&&p.variants.length)classification+='<br><br>Commercial variants:<br>'+p.variants.join('<br>');document.getElementById('product-classification').innerHTML=classification;if(p.specs&&p.specs.length){document.getElementById('spec-heading').textContent='Reference Specification';document.getElementById('product-specification').innerHTML=p.specs.map(s=>'<strong>'+s[0]+':</strong> '+s[1]).join('<br>');}else{document.getElementById('spec-heading').textContent='Specification Reviewed per Requirement';document.getElementById('product-specification').textContent='No generic technical specification is published for this inquiry route. Send the required grade or target specification for commercial review.';}const subject='Industrial RFQ — '+p.name+(p.abbr?' ('+p.abbr+')':'');const body=['Product: '+p.name,'Grade: ','Quantity: ','Destination: ','Timing: ','Specification: ','Contact: ','','Please review this requirement and advise next commercial steps.'].join('\\n');const request=document.getElementById('request-spec');request.textContent='Start commercial inquiry';request.href='mailto:sales@uniqueholding.com.tr?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);})();</script>`;
if(!/<script src="assets\/products-data\.js"><\/script><script>\(function\(\)\{[\s\S]*?\}\)\(\);<\/script>/.test(product))throw new Error('Product script pattern missing');
product=product.replace(/<script src="assets\/products-data\.js"><\/script><script>\(function\(\)\{[\s\S]*?\}\)\(\);<\/script>/,productScript);

const css=`@layer page{
html{scroll-behavior:auto}.catalog-anchor{scroll-margin-top:96px}
.products-hero{min-height:72svh}.products-hero .inner{padding-bottom:86px}.products-hero .intro{max-width:820px}.products-hero-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:28px}.products-hero-actions a{display:inline-flex;align-items:center;min-height:42px;padding:0 14px;border:1px solid rgba(255,255,255,.28);font-size:9px;letter-spacing:.14em;text-transform:uppercase}.products-hero-actions a:first-child{background:#ee6a24;border-color:#ee6a24;color:#080a0b;font-weight:700}
.product-ia-path{background:#0b0e0f;border-top:1px solid rgba(255,255,255,.12);border-bottom:1px solid rgba(255,255,255,.12);padding:0 max(32px,calc((100vw - 1540px)/2))}.product-ia-path ol{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:repeat(4,1fr)}.product-ia-path li{min-width:0;border-left:1px solid rgba(255,255,255,.12)}.product-ia-path li:last-child{border-right:1px solid rgba(255,255,255,.12)}.product-ia-path a{min-height:150px;padding:26px 24px;display:flex;flex-direction:column;gap:7px}.product-ia-path small,.product-family-nav small,.product-route-context small{color:#ee6a24;font-size:8px;letter-spacing:.16em;text-transform:uppercase}.product-ia-path strong{font:400 22px/1.08 Georgia,'Times New Roman',serif}.product-ia-path span{margin-top:auto;color:#858d8f;font-size:11px;line-height:1.5}
.product-section-cap{margin-bottom:38px}.core-distinction{display:grid;grid-template-columns:.32fr 1fr;gap:32px;border-top:1px solid rgba(255,255,255,.18);padding:20px 0 28px;margin-bottom:12px}.core-distinction>span{color:#ee6a24;font-size:9px;letter-spacing:.17em;text-transform:uppercase}.core-distinction p{margin:0;max-width:760px;color:#9ca3a5;line-height:1.7}
#core-grid{counter-reset:core;gap:22px;background:none;border:0}#core-grid .product-link{counter-increment:core;position:relative;min-height:350px;padding:34px 30px;background:#101517;border-top:1px solid rgba(255,255,255,.22);border-bottom:1px solid rgba(255,255,255,.09)}#core-grid .product-link:before{content:'0' counter(core);position:absolute;right:28px;top:26px;color:#596164;font:400 42px/1 Georgia,'Times New Roman',serif}#core-grid .product-link small{max-width:70%;font-size:9px}#core-grid .product-link h3{font-size:clamp(34px,3.2vw,52px);line-height:.98;margin:92px 0 12px;max-width:85%}#core-grid .product-link p{font-size:13px;color:#adb3b5}#core-grid .product-link span{color:#f2eee7;font-size:9px;border-top:1px solid rgba(255,255,255,.14);padding-top:18px}
.catalog-scope{display:grid;grid-template-columns:.28fr 1fr 1fr;gap:24px;padding:20px 0;border-top:1px solid rgba(255,255,255,.18);border-bottom:1px solid rgba(255,255,255,.18);margin-bottom:34px}.catalog-scope strong{color:#ee6a24;font-size:9px;letter-spacing:.16em;text-transform:uppercase}.catalog-scope span{font-size:12px;line-height:1.65;color:#a0a7a9}
.product-family-nav{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:rgba(255,255,255,.14);border:1px solid rgba(255,255,255,.14);margin-bottom:28px}.product-family-nav a{background:#111617;padding:23px;min-height:140px;display:flex;flex-direction:column;gap:8px}.product-family-nav strong{font:400 24px/1.08 Georgia,'Times New Roman',serif}.product-family-nav span{margin-top:auto;color:#858d8f;font-size:10px;line-height:1.5}
.catalog-tools{padding:18px 0 22px;margin:0;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:20px;align-items:end;border-bottom:1px solid rgba(255,255,255,.14)}.catalog-tools label{display:block}.catalog-tools label>span{display:block;margin-bottom:8px;color:#8f9799;font-size:8px;letter-spacing:.15em;text-transform:uppercase}.catalog-search{width:100%;max-width:none;min-height:50px}.catalog-status{display:flex;gap:14px;align-items:center;padding-bottom:2px}.catalog-clear{min-height:42px;padding:0 13px;border:1px solid rgba(255,255,255,.22);background:transparent;color:#ece8df;font-size:9px;letter-spacing:.12em;text-transform:uppercase}.catalog-clear:disabled{opacity:.35}.catalog-clear:focus-visible,.product-family-nav a:focus-visible,.product-ia-path a:focus-visible,#core-grid .product-link:focus-visible,#catalog .product-link:focus-visible{outline:2px solid #ff7a2e;outline-offset:3px}.catalog-empty{margin:24px 0 0;padding:18px 20px;border:1px solid rgba(255,255,255,.14);color:#aab0b2}
#catalog>.catalog-group{margin:0;padding:68px 0 76px;border-bottom:1px solid rgba(255,255,255,.14)}#catalog>.catalog-group>h2{max-width:980px;margin-bottom:16px}#catalog>.catalog-group>p{max-width:900px;margin-bottom:42px}.catalog-group[data-catalog-family]{display:grid;grid-template-columns:minmax(190px,.34fr) 1fr;gap:34px;align-items:start;margin:0;padding:24px 0;border-top:1px solid rgba(255,255,255,.11)}.catalog-group[data-catalog-family]>.subsite-label{margin:7px 0 0;color:#b4b9ba;font-size:9px;line-height:1.55}.catalog-group[data-catalog-family]>.product-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0;background:none;border:0;border-left:1px solid rgba(255,255,255,.1)}#catalog .product-link{min-height:98px;padding:15px 16px;background:transparent;border-right:1px solid rgba(255,255,255,.1);border-bottom:1px solid rgba(255,255,255,.1);display:grid;grid-template-columns:minmax(0,1fr) auto;grid-template-areas:'name meta' 'abbr route';gap:5px 14px;align-content:center}#catalog .product-link:hover{background:#141a1c;transform:none}#catalog .product-link small{display:none}#catalog .product-link h3{grid-area:name;margin:0;font-size:18px;line-height:1.18;letter-spacing:-.015em;overflow-wrap:anywhere}#catalog .product-link p{grid-area:abbr;align-self:end;font-size:10px;color:#8f9799;line-height:1.4}#catalog .product-link span{grid-area:route;align-self:end;margin:0;font-size:8px;color:#bfc4c5;white-space:nowrap}#catalog .product-link:after{content:'Inquiry';grid-area:meta;align-self:start;color:#ee6a24;font-size:7px;letter-spacing:.14em;text-transform:uppercase}
.product-rfq{background:#111617}.product-rfq-grid{display:grid;grid-template-columns:1fr .75fr;gap:80px;align-items:end}.product-rfq h2{font:400 clamp(42px,5vw,74px)/.98 Georgia,'Times New Roman',serif;letter-spacing:-.045em;margin:18px 0 0}.product-rfq p{color:#a0a7a9;line-height:1.8;margin:0 0 28px}
.product-route-context{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr) auto minmax(0,1fr);gap:12px;align-items:stretch;margin:0 0 48px;padding:12px 0;border-top:1px solid rgba(255,255,255,.14);border-bottom:1px solid rgba(255,255,255,.14)}.product-route-context>div,.product-route-context>a{min-width:0;padding:10px 12px;display:flex;flex-direction:column;gap:7px}.product-route-context i{align-self:center;color:#596164;font-style:normal}.product-route-context span{font-size:12px;line-height:1.45;color:#d6d9d9;overflow-wrap:anywhere}.detail-breadcrumb{display:flex;gap:9px;flex-wrap:wrap;align-items:center;margin-bottom:28px;color:#939b9d;font-size:9px;letter-spacing:.1em;text-transform:uppercase}.detail-breadcrumb a{color:#d8dcdd}.detail-breadcrumb a:focus-visible,.product-route-context a:focus-visible{outline:2px solid #ff7a2e;outline-offset:3px}
@media(max-width:1100px){.product-ia-path ol{grid-template-columns:repeat(2,1fr)}.product-ia-path li:nth-child(3){border-top:1px solid rgba(255,255,255,.12)}.product-ia-path li:nth-child(4){border-top:1px solid rgba(255,255,255,.12)}.product-family-nav{grid-template-columns:1fr}.product-family-nav a{min-height:110px}.catalog-group[data-catalog-family]{grid-template-columns:1fr;gap:14px}.catalog-group[data-catalog-family]>.product-grid{border-left:0}.product-rfq-grid{grid-template-columns:1fr;gap:32px}.catalog-scope{grid-template-columns:1fr 1fr}.catalog-scope strong{grid-column:1/-1}}
@media(max-width:700px){.products-hero{min-height:660px}.products-hero .inner{padding-bottom:72px}.products-hero-actions{max-width:230px}.product-ia-path{padding:0 18px}.product-ia-path ol{grid-template-columns:1fr}.product-ia-path li,.product-ia-path li:last-child{border-left:0;border-right:0;border-top:1px solid rgba(255,255,255,.12)}.product-ia-path li:first-child{border-top:0}.product-ia-path a{min-height:112px;padding:20px 4px}.core-distinction{grid-template-columns:1fr;gap:10px}#core-grid{grid-template-columns:1fr;gap:14px}#core-grid .product-link{min-height:270px;padding:26px 22px}#core-grid .product-link:before{right:20px;font-size:34px}#core-grid .product-link h3{margin-top:76px;font-size:38px}.catalog-scope{grid-template-columns:1fr;gap:10px}.catalog-scope strong{grid-column:auto}.catalog-tools{grid-template-columns:1fr;gap:12px}.catalog-status{justify-content:space-between}.catalog-group[data-catalog-family]>.product-grid{grid-template-columns:1fr}#catalog>.catalog-group{padding:56px 0 64px}#catalog .product-link{min-height:86px;padding:14px 2px 14px 0;border-right:0;grid-template-columns:minmax(0,1fr) auto;gap:5px 10px}#catalog .product-link h3{font-size:17px}#catalog .product-link span{font-size:7px}.product-route-context{grid-template-columns:1fr;margin-bottom:38px}.product-route-context i{display:none}.product-route-context>div,.product-route-context>a{padding:10px 0;border-bottom:1px solid rgba(255,255,255,.08)}.product-rfq{padding-top:80px;padding-bottom:80px}}
}
`;
write('assets/products-ia.css',css);

qa=replace(qa,
  "const verifyCard=(p,kind,cards)=>{\n  const card=cards.find(c=>attr(c,'data-slug')===p.slug);",
  "const coreReferenceRoutes={'urea-46':'urea-46.html','caustic-soda-solid':'caustic-soda-solid.html','sodium-sulphate-anhydrous':'sodium-sulphate-anhydrous.html'};\nconst verifyCard=(p,kind,cards)=>{\n  const card=cards.find(c=>attr(c,'data-slug')===p.slug);",
  'core route QA map');
qa=replace(qa,
  "  const expectedHref='product.html?slug='+encodeURIComponent(p.slug);",
  "  const expectedHref=kind==='core'?coreReferenceRoutes[p.slug]:'product.html?slug='+encodeURIComponent(p.slug);",
  'core/inquiry href QA');

const phase09Qa=`
// Phase 09 — Products Information Architecture guards.
const productsMain=products.match(/<main\\b[\\s\\S]*?<\\/main>/i)?.[0]||'';
const productDetail=read('product.html');
const productsCss=read('assets/products-ia.css');
if(!products.includes('assets/products-ia.css')||!productDetail.includes('assets/products-ia.css'))errors.push('Phase 09: Products IA stylesheet must load on index and inquiry detail routes');
if(!productsCss.startsWith('@layer page{'))errors.push('assets/products-ia.css: Phase 09 page layer missing');
for(const token of ['product-ia-path','Core Industrial Products','Product Families','Product Inquiry Routes','Industrial Sales / RFQ','catalog-scope','product-family-nav','catalog-empty','product-rfq'])if(!products.includes(token))errors.push('products.html: Phase 09 IA token missing -> '+token);
for(const token of ['product-route-context','detail-breadcrumb','coreRoutes','location.replace(coreRoutes[slug])','Start commercial inquiry'])if(!productDetail.includes(token))errors.push('product.html: Phase 09 inquiry-route context missing -> '+token);
for(const [slug,href] of Object.entries(coreReferenceRoutes)){
  const card=staticCore.find(c=>attr(c,'data-slug')===slug);
  if(!card||attr(card,'href')!==href||attr(card,'data-destination')!=='reference-detail')errors.push('products.html: Phase 09 REFERENCE DETAIL route invalid -> '+slug);
  if(!fs.existsSync(path.join(root,href)))errors.push('products.html: Phase 09 reference destination missing -> '+href);
}
for(const card of staticInquiry){
  const slug=attr(card,'data-slug');
  if(attr(card,'data-destination')!=='inquiry-detail')errors.push('products.html: Phase 09 inquiry route classification missing -> '+slug);
  if(attr(card,'href')!=='product.html?slug='+encodeURIComponent(slug))errors.push('products.html: Phase 09 INQUIRY DETAIL destination invalid -> '+slug);
}
const routeAudit={referenceDetail:staticCore.length,inquiryDetail:staticInquiry.length,industrialSales:(productsMain.match(/href=["']sales\\.html["']/gi)||[]).length,invalid:0};
if(routeAudit.referenceDetail!==3||routeAudit.inquiryDetail!==62)errors.push('products.html: Phase 09 route audit count regression');
console.log('PHASE 09 ROUTE AUDIT: REFERENCE DETAIL='+routeAudit.referenceDetail+' / INQUIRY DETAIL='+routeAudit.inquiryDetail+' / INVALID='+routeAudit.invalid);
for(const html of [['products.html',products],['product.html',productDetail]]){
  const ids=[...html[1].matchAll(/\\bid=["']([^"']+)["']/gi)].map(m=>m[1]);
  const dup=[...new Set(ids.filter((id,i)=>ids.indexOf(id)!==i))];
  if(dup.length)errors.push(html[0]+': duplicate IDs -> '+dup.join(', '));
}
for(const forbidden of [/\\bin stock\\b/i,/\\bavailable now\\b/i,/\\bdirect producer\\b/i,/\\bour production\\b/i,/\\bour factory\\b/i,/\\bour warehouse\\b/i,/\\bour terminal\\b/i,/\\bour plant\\b/i,/\\bguaranteed supply\\b/i,/\\bexclusive supplier\\b/i,/\\bglobal supplier\\b/i,/\\bleading supplier\\b/i,/\\bcertified supplier\\b/i]){
  if(forbidden.test(productsMain)||forbidden.test(productDetail))errors.push('Phase 09: unsupported Products-area inventory/ownership wording -> '+forbidden);
}
if(/https?:\\/\\//i.test(productsCss))errors.push('assets/products-ia.css: external media/dependency request is forbidden');
if(/alignHashTarget|requestAnimationFrame\\s*\\(|setTimeout\\s*\\(|MutationObserver\\s*\\(|window\\.scrollTo\\s*\\(/.test(products))errors.push('products.html: Phase 09 must preserve native fragment navigation without timing workaround');
if(!products.includes("clear.addEventListener('click'"))errors.push('products.html: Phase 09 explicit search reset missing');
if(!products.includes("empty.hidden=visible!==0"))errors.push('products.html: Phase 09 no-results state missing');
if(!products.includes('aria-live="polite"'))errors.push('products.html: Phase 09 search status must be announced');
`;
qa=replace(qa,"\nif(errors.length){console.error('\\nTECHNICAL QA FAILED');",phase09Qa+"\nif(errors.length){console.error('\\nTECHNICAL QA FAILED');",'Phase 09 QA insertion');

write('products.html',products);
write('product.html',product);
write('scripts/qa-site.mjs',qa);
console.log('Phase 09 product IA files written from '+BASE);
