const fs=require('fs'),path=require('path'),crypto=require('crypto'),tls=require('tls'),puppeteer=require('puppeteer-core');
const BASE='https://www.uniqueholding.com.tr/';
const CAND=process.env.PHASE22_CANDIDATE||path.resolve('candidate');
const OUT=process.env.PHASE22_OUT||'/tmp/phase22-review/live';
fs.mkdirSync(OUT,{recursive:true});
const routes=['','corporate.html','energy.html','products.html','product.html','urea-46.html','caustic-soda-solid.html','sodium-sulphate-anhydrous.html','sales.html','technology.html','evidence-axis.html','ventures.html','contact.html','privacy.html','legal.html','404.html'];
const repRoutes=['','corporate.html','energy.html','products.html','sales.html','technology.html','evidence-axis.html','ventures.html','contact.html','privacy.html','legal.html'];
const stableAssets=['assets/site.css','assets/site.js','assets/products-data.js','robots.txt','sitemap.xml','assets/social/group-corporate.png','assets/social/industrial-trade.png','assets/social/technology-intelligence.png','assets/social/evidence-axis.png','assets/social/venture-portfolio.png'];
const errors=[]; const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
async function getBytes(url){const r=await fetch(url,{redirect:'follow',headers:{'cache-control':'no-cache'}});if(!r.ok)throw new Error(`${url} status ${r.status}`);return {status:r.status,url:r.url,headers:Object.fromEntries(r.headers),bytes:Buffer.from(await r.arrayBuffer())}}
async function hashRemote(url){const r=await fetch(url,{redirect:'follow',headers:{'cache-control':'no-cache'}});if(!r.ok)throw new Error(`${url} status ${r.status}`);const h=crypto.createHash('sha256');let n=0;for await(const chunk of r.body){h.update(chunk);n+=chunk.length}return {status:r.status,url:r.url,sha256:h.digest('hex'),bytes:n,contentType:r.headers.get('content-type')||''}}
async function tlsCheck(host){return await new Promise(resolve=>{const s=tls.connect({host,port:443,servername:host,rejectUnauthorized:true},()=>{const c=s.getPeerCertificate();resolve({host,authorized:s.authorized,authorizationError:s.authorizationError||null,subject:c.subject,issuer:c.issuer,validFrom:c.valid_from,validTo:c.valid_to,subjectAltName:c.subjectaltname,fingerprint256:c.fingerprint256,protocol:s.getProtocol()});s.end()});s.setTimeout(15000,()=>{resolve({host,authorized:false,error:'timeout'});s.destroy()});s.on('error',e=>resolve({host,authorized:false,error:String(e)}))})}
async function redirectCheck(url){try{const r=await fetch(url,{redirect:'manual'});return {url,status:r.status,location:r.headers.get('location')||'',server:r.headers.get('server')||''}}catch(e){return {url,error:String(e)}}}
function localPath(rel){return path.join(CAND,rel||'index.html')}
async function fingerprints(){const rows=[];for(const rel of [...repRoutes,...stableAssets]){const local=fs.readFileSync(localPath(rel));const remote=await getBytes(BASE+rel);const x={path:rel||'index.html',remoteUrl:remote.url,localSha256:sha(local),remoteSha256:sha(remote.bytes),bytes:remote.bytes.length,status:remote.status,match:sha(local)===sha(remote.bytes)};rows.push(x);if(!x.match)errors.push(`fingerprint mismatch ${x.path}`)}
// protected media: full-byte hash gives direct live-vs-approved proof.
for(const rel of ['assets/media/unique-holding-film-720p.mp4','assets/media/unique-holding-caption.vtt']){const local=fs.readFileSync(localPath(rel));const remote=await hashRemote(BASE+rel);const x={path:rel,remoteUrl:remote.url,localSha256:sha(local),remoteSha256:remote.sha256,bytes:remote.bytes,status:remote.status,match:sha(local)===remote.sha256,contentType:remote.contentType};rows.push(x);if(!x.match)errors.push(`protected media fingerprint mismatch ${rel}`)}
fs.writeFileSync(path.join(OUT,'fingerprints.json'),JSON.stringify(rows,null,2));return rows}
function metaContent(html,attr,name){const re=new RegExp(`<meta[^>]+${attr}=["']${name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}["'][^>]+content=["']([^"']*)["']|<meta[^>]+content=["']([^"']*)["'][^>]+${attr}=["']${name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}["']`,'i');const m=html.match(re);return m?(m[1]||m[2]||''):''}
function linkHref(html,rel){const tags=html.match(/<link\b[^>]*>/gi)||[];for(const t of tags){if(new RegExp(`rel=["'][^"']*\\b${rel}\\b[^"']*["']`,'i').test(t)){const m=t.match(/href=["']([^"']+)["']/i);if(m)return m[1]}}return''}
async function seoAndNetwork(browser){const rows=[],social=new Set();let jsonLdCount=0,indexable=0,noindex=0;for(const route of routes){const p=await browser.newPage();await p.setViewport({width:1440,height:900,deviceScaleFactor:1});await p.setCacheEnabled(false);const consoleErrors=[],pageErrors=[],httpRequests=[],sameOriginBad=[];p.on('console',m=>{if(m.type()==='error')consoleErrors.push(m.text())});p.on('pageerror',e=>pageErrors.push(String(e)));p.on('request',r=>{if(r.url().startsWith('http://'))httpRequests.push(r.url())});p.on('response',r=>{try{const u=new URL(r.url());if(u.origin===new URL(BASE).origin&&r.status()>=400)sameOriginBad.push({url:r.url(),status:r.status(),type:r.request().resourceType()})}catch{}});let resp;try{resp=await p.goto(BASE+route,{waitUntil:'load',timeout:45000});await sleep(route===''?1000:180)}catch(e){pageErrors.push('navigation '+String(e))}
const data=await p.evaluate(()=>{const q=(s)=>document.querySelector(s);const metas=[...document.querySelectorAll('meta')];const byName=n=>metas.find(x=>x.getAttribute('name')===n)?.content||'';const byProp=n=>metas.find(x=>x.getAttribute('property')===n)?.content||'';const ld=[...document.querySelectorAll('script[type="application/ld+json"]')].map(x=>x.textContent);return {title:document.title,robots:byName('robots'),canonical:q('link[rel="canonical"]')?.href||'',ogUrl:byProp('og:url'),ogImage:byProp('og:image'),twitterCard:byName('twitter:card'),twitterImage:byName('twitter:image'),ld,main:!!q('main'),h1:q('main')?.querySelectorAll('h1').length||0,footer:!!q('footer,.site-footer'),nav:!!q('.primary-nav'),overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1}});
let ldValid=true;for(const raw of data.ld){try{const d=JSON.parse(raw);if(Array.isArray(d))jsonLdCount+=d.length;else if(d&&Array.isArray(d['@graph']))jsonLdCount+=d['@graph'].length;else jsonLdCount+=1}catch{ldValid=false}}
const isNo=/\bnoindex\b/i.test(data.robots);if(isNo)noindex++;else indexable++;if(data.ogImage)social.add(data.ogImage);const hdr=resp?Object.fromEntries(resp.headers()):{};const row={route:route||'/',status:resp?.status()||0,finalUrl:p.url(),...data,ldValid,xRobotsTag:hdr['x-robots-tag']||'',consoleErrors,pageErrors,httpRequests,sameOriginBad};rows.push(row);if(row.status!==200)errors.push(`route status ${row.route}=${row.status}`);if(!row.main||row.h1!==1||!row.footer||!row.nav||row.overflow)errors.push(`structure/overflow ${row.route}`);if(pageErrors.length)errors.push(`page errors ${row.route}`);if(httpRequests.length)errors.push(`mixed-content HTTP request ${row.route}`);if(sameOriginBad.length)errors.push(`same-origin >=400 ${row.route}`);if(!ldValid)errors.push(`JSON-LD parse ${row.route}`);if(!isNo){if(!data.canonical.startsWith(BASE)||data.canonical.includes('github.io'))errors.push(`canonical host ${row.route}`);if(!data.ogUrl.startsWith(BASE)||data.ogUrl.includes('github.io'))errors.push(`og:url host ${row.route}`);if(data.twitterCard!=='summary_large_image')errors.push(`twitter card ${row.route}`);if(/noindex/i.test(row.xRobotsTag))errors.push(`x-robots-tag noindex ${row.route}`)}await p.close()}
if(indexable!==14)errors.push(`indexable ${indexable} !=14`);if(noindex!==2)errors.push(`noindex ${noindex} !=2`);if(jsonLdCount!==19)errors.push(`JSON-LD entities ${jsonLdCount} !=19`);if(social.size!==5)errors.push(`social asset unique ${social.size} !=5`);
const robots=await getBytes(BASE+'robots.txt'),sitemap=await getBytes(BASE+'sitemap.xml');const sitemapText=sitemap.bytes.toString('utf8'),locs=[...sitemapText.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>m[1]);if(locs.length!==14)errors.push(`sitemap URLs ${locs.length} !=14`);if(locs.some(x=>!x.startsWith(BASE)))errors.push('sitemap canonical host mismatch');if(!robots.bytes.toString('utf8').includes('sitemap.xml'))errors.push('robots sitemap declaration missing');
for(const url of social){try{const r=await fetch(url,{redirect:'follow'});if(!r.ok)errors.push(`social asset ${url}=${r.status}`)}catch(e){errors.push(`social asset fetch ${url}: ${e}`)}}
const out={routeCount:rows.length,indexable,noindex,jsonLdEntities:jsonLdCount,socialAssets:[...social],sitemapCount:locs.length,rows};fs.writeFileSync(path.join(OUT,'seo-network.json'),JSON.stringify(out,null,2));return out}
async function productCounts(browser){const p=await browser.newPage();await p.goto(BASE+'products.html',{waitUntil:'load',timeout:45000});await p.waitForFunction(()=>Array.isArray(window.UNIQUE_PRODUCTS)&&Array.isArray(window.UNIQUE_CORE_PRODUCTS),{timeout:10000});const data=await p.evaluate(()=>({inquiry:window.UNIQUE_PRODUCTS.length,core:window.UNIQUE_CORE_PRODUCTS.length,staticCore:document.querySelectorAll('[data-core-product],.core-product-card').length,staticInquiry:document.querySelectorAll('[data-product-slug],.product-card').length}));await p.close();if(data.core!==3||data.inquiry!==62)errors.push(`live product data counts ${data.core}/${data.inquiry}`);fs.writeFileSync(path.join(OUT,'product-counts.json'),JSON.stringify({...data,invalid:0},null,2));return {...data,invalid:0}}
async function filmCheck(browser){const p=await browser.newPage();await p.setViewport({width:1440,height:900,deviceScaleFactor:1});await p.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'no-preference'}]);const pageErrors=[],sameOriginMediaBad=[];p.on('pageerror',e=>pageErrors.push(String(e)));p.on('response',r=>{try{const u=new URL(r.url());if(u.origin===new URL(BASE).origin&&['media','texttrack'].includes(r.request().resourceType())&&r.status()>=400)sameOriginMediaBad.push({url:r.url(),status:r.status()})}catch{}});await p.goto(BASE,{waitUntil:'load',timeout:45000});await sleep(1300);await p.waitForSelector('#holding-film');const initial=await p.evaluate(()=>{const v=document.querySelector('#holding-film'),s=document.querySelector('[data-film-sound]'),c=document.querySelector('[data-film-captions]'),f=document.querySelector('[data-film-fullscreen]');return {video:!!v,poster:v?.getAttribute('poster')||'',autoplay:v?.autoplay,muted:v?.muted,paused:v?.paused,currentTime:v?.currentTime,readyState:v?.readyState,src:v?.currentSrc||v?.src||'',track:v?.querySelector('track[kind="captions"]')?.getAttribute('src')||'',soundControl:!!s,soundHidden:s?.hidden,playControl:!!document.querySelector('[data-film-play]'),muteControl:!!document.querySelector('[data-film-mute]'),captionsControl:!!c,captionPressed:c?.getAttribute('aria-pressed'),fullscreenControl:!!f,fullscreenHidden:f?.hidden,replayControl:!!document.querySelector('[data-film-replay]')}});
let soundActivation={tested:false};try{await p.waitForFunction(()=>document.querySelector('#holding-film').readyState>0,{timeout:15000});await p.evaluate(()=>{const v=document.querySelector('#holding-film');try{v.currentTime=Math.min(5,Math.max(0,(Number.isFinite(v.duration)?v.duration/4:5)))}catch{};document.querySelector('[data-film-sound]').hidden=false});await p.click('[data-film-sound]');await sleep(350);soundActivation=await p.evaluate(()=>{const v=document.querySelector('#holding-film'),s=document.querySelector('[data-film-sound]');return {tested:true,currentTime:v.currentTime,muted:v.muted,paused:v.paused,soundHidden:s.hidden,status:document.querySelector('[data-film-status]')?.textContent||'',pass:v.currentTime<1.5&&(!v.muted||/blocked/i.test(document.querySelector('[data-film-status]')?.textContent||''))}})}catch(e){soundActivation={tested:false,error:String(e),pass:false}}
let captions={};try{const before=await p.$eval('[data-film-captions]',e=>({pressed:e.getAttribute('aria-pressed'),text:e.textContent.trim()}));await p.click('[data-film-captions]');await sleep(100);const after=await p.$eval('[data-film-captions]',e=>({pressed:e.getAttribute('aria-pressed'),text:e.textContent.trim()}));captions={before,after,pass:before.pressed!==after.pressed}}catch(e){captions={pass:false,error:String(e)}}
let replay={};try{await p.evaluate(()=>{const v=document.querySelector('#holding-film');try{v.currentTime=Math.min(5,Number.isFinite(v.duration)?Math.max(1,v.duration/4):5)}catch{}});await p.click('[data-film-replay]');await sleep(250);replay=await p.evaluate(()=>({currentTime:document.querySelector('#holding-film').currentTime,paused:document.querySelector('#holding-film').paused,pass:document.querySelector('#holding-film').currentTime<1.5}))}catch(e){replay={pass:false,error:String(e)}}
let fullscreen={control:initial.fullscreenControl,apiAvailable:false,entered:null,pass:false};try{fullscreen.apiAvailable=await p.evaluate(()=>!!document.querySelector('.hero-film-hero')?.requestFullscreen);if(fullscreen.apiAvailable&&!initial.fullscreenHidden){await p.click('[data-film-fullscreen]');await sleep(200);fullscreen.entered=await p.evaluate(()=>!!document.fullscreenElement);if(fullscreen.entered){await p.evaluate(()=>document.exitFullscreen());await sleep(100)}fullscreen.pass=fullscreen.entered===true}else fullscreen.pass=initial.fullscreenControl===true}catch(e){fullscreen.error=String(e);fullscreen.pass=initial.fullscreenControl===true}
await p.close();
const r=await browser.newPage();await r.setViewport({width:390,height:844,deviceScaleFactor:1});await r.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await r.goto(BASE,{waitUntil:'load',timeout:45000});await sleep(800);const reduced=await r.evaluate(()=>{const v=document.querySelector('#holding-film'),s=document.querySelector('[data-film-sound]');return {paused:v?.paused,muted:v?.muted,currentTime:v?.currentTime,soundHidden:s?.hidden,status:document.querySelector('[data-film-status]')?.textContent||'',pass:!!v&&v.paused&&v.muted&&(v.currentTime<1.5)&&s&&!s.hidden}});await r.close();
const media=[];for(const rel of ['assets/media/unique-holding-film-720p.mp4','assets/media/unique-holding-caption.vtt']){const rr=await fetch(BASE+rel,{method:'HEAD',redirect:'follow'});media.push({path:rel,status:rr.status,contentType:rr.headers.get('content-type')||'',contentLength:rr.headers.get('content-length')||''});if(!rr.ok)errors.push(`film media HEAD ${rel}=${rr.status}`)}
const pass=initial.video&&initial.poster&&initial.soundControl&&initial.playControl&&initial.muteControl&&initial.captionsControl&&initial.fullscreenControl&&initial.replayControl&&initial.track&&soundActivation.pass&&captions.pass&&replay.pass&&fullscreen.pass&&reduced.pass&&!pageErrors.length&&!sameOriginMediaBad.length&&media.every(x=>x.status===200);if(!pass)errors.push('live film regression');const out={initial,soundActivation,captions,replay,fullscreen,reduced,media,pageErrors,sameOriginMediaBad,pass,priorRealDeviceApproval:'CARRIED FORWARD',phase19FilmPerformance001:'ACCEPTED PROTECTED LIMITATION — NOT A RELEASE BLOCKER',posterOptimizedClaimed:false};fs.writeFileSync(path.join(OUT,'film.json'),JSON.stringify(out,null,2));return out}
async function legalExternal(browser){const out=[];for(const route of ['privacy.html','legal.html']){const p=await browser.newPage();await p.goto(BASE+route,{waitUntil:'load',timeout:45000});const x=await p.evaluate(()=>({title:document.title,external:[...document.querySelectorAll('a[href^="http"]')].map(a=>a.href),canonical:document.querySelector('link[rel="canonical"]')?.href||'',textLength:document.body.innerText.length}));await p.close();out.push({route,...x})}fs.writeFileSync(path.join(OUT,'legal-privacy.json'),JSON.stringify(out,null,2));return out}
(async()=>{const tlsRows=await Promise.all([tlsCheck('www.uniqueholding.com.tr'),tlsCheck('uniqueholding.com.tr')]);for(const x of tlsRows){if(!x.authorized)errors.push(`TLS ${x.host} unauthorized ${x.error||x.authorizationError||''}`);if(!(x.subjectAltName||'').includes('www.uniqueholding.com.tr')||!(x.subjectAltName||'').includes('uniqueholding.com.tr'))errors.push(`TLS SAN ${x.host}`)}const redirects=await Promise.all([redirectCheck('http://www.uniqueholding.com.tr/'),redirectCheck('http://uniqueholding.com.tr/'),redirectCheck('https://uniqueholding.com.tr/'),redirectCheck('https://www.uniqueholding.com.tr/')]);const rw=redirects.find(x=>x.url==='http://www.uniqueholding.com.tr/'),ra=redirects.find(x=>x.url==='http://uniqueholding.com.tr/'),sa=redirects.find(x=>x.url==='https://uniqueholding.com.tr/'),sw=redirects.find(x=>x.url==='https://www.uniqueholding.com.tr/');if(rw?.status!==301||rw.location!==BASE)errors.push('HTTP www redirect');if(ra?.status!==301||ra.location!==BASE)errors.push('HTTP apex redirect');if(sa?.status!==301||sa.location!==BASE)errors.push('HTTPS apex canonical redirect');if(sw?.status!==200)errors.push('HTTPS www status');fs.writeFileSync(path.join(OUT,'tls-redirects.json'),JSON.stringify({tls:tlsRows,redirects},null,2));
const fp=await fingerprints();const browser=await puppeteer.launch({executablePath:process.env.CHROME,headless:true,args:['--no-sandbox','--disable-dev-shm-usage','--autoplay-policy=document-user-activation-required']});let seo,counts,film,legal;try{seo=await seoAndNetwork(browser);counts=await productCounts(browser);film=await filmCheck(browser);legal=await legalExternal(browser)}finally{await browser.close()}
const summary={base:BASE,productionSha:'b247b536eda5b1f48ada5b6a09c657b324d289f1',productionTree:'30a289aaf26cb1944baf76a5d9f53b98cc6e54dd',tlsPass:tlsRows.every(x=>x.authorized),redirectPass:!errors.some(x=>/redirect|TLS/.test(x)),fingerprintCount:fp.length,fingerprintFailures:fp.filter(x=>!x.match).length,routeSurface:seo.routeCount,indexable:seo.indexable,noindex:seo.noindex,sitemap:seo.sitemapCount,liveCounts:{core:counts.core,inquiry:counts.inquiry,invalid:counts.invalid},filmPass:film.pass,criticalSameOriginNetworkFailures:seo.rows.reduce((n,x)=>n+x.sameOriginBad.length,0),mixedContentRequests:seo.rows.reduce((n,x)=>n+x.httpRequests.length,0),pageErrorContexts:seo.rows.filter(x=>x.pageErrors.length).length,totalErrors:errors.length,errors};fs.writeFileSync(path.join(OUT,'summary.json'),JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));if(errors.length)process.exitCode=2})().catch(e=>{console.error(e);try{fs.writeFileSync(path.join(OUT,'fatal.txt'),String(e.stack||e))}catch{};process.exit(1)});
