from pathlib import Path
import json, os, statistics
P=Path(os.environ['PHASE19_PACKET']); new=os.environ['NEW_SHA']; main=os.environ['MAIN_SHA']; rebuild=os.environ['REBUILD_SHA']
s=json.loads((P/'phase19-summary.json').read_text()); g=json.loads((P/'regression/phase19-regression.json').read_text())
files=(P/'reports/exact-files-changed.txt').read_text().strip().splitlines()
lines=['# PHASE 19 — REVIEW PACKET','', 'STATUS: READY FOR EXTERNAL REVIEW','', 'BASELINE SHA:', '`8d2811298c668865f5438f86337c9d8f9d959c80`','', 'NEW SHA:',f'`{new}`','']
def add(n,title,body): lines.extend([f'## {n}. {title}','',body,''])
add(1,'EXACT FILES CHANGED','\n'.join(f'- `{x}`' for x in files))
add(2,'PERFORMANCE BASELINE',f"18 representative route/viewport combinations, two cold local runs each. Baseline axe contexts: {s['baselineAxe']['contexts']}. Full metrics: `docs/qa/phase19-performance-audit.md` and `before/phase19-baseline.json`.")
add(3,'PERFORMANCE AFTER','Same measurement harness and route/viewports. Structural goal passed: CSS dependency requests removed; duplicate homepage image preload removed; no new third-party requests. Full metrics in the performance audit.')
rows=['| Route | Viewport | Requests before → after | Transfer before → after | Image bytes before → after | Third-party before → after | CLS before → after | LCP observation |','|---|---:|---:|---:|---:|---:|---:|---|']
for r in s['routeMetrics']:
 b,a=r['before'],r['after']; rows.append(f"| {r['route']} | {r['viewport']} | {b['requests']} → {a['requests']} | {b['transfer']:,} → {a['transfer']:,} B | {b['image']:,} → {a['image']:,} B | {b['thirdParty']} → {a['thirdParty']} | {b['cls']:.5f} → {a['cls']:.5f} | {b['lcp']:.0f} → {a['lcp']:.0f} ms local observation |")
add(4,'BEFORE / AFTER ROUTE METRICS','\n'.join(rows))
add(5,'REQUEST / TRANSFER AUDIT','PASS. Three render-blocking CSS `@import` dependencies were flattened into their existing cascade layers. Homepage duplicate Unsplash preload was removed. No timing-score claim is made from single-environment synthetic results.')
add(6,'MEDIA INVENTORY','Complete rendered-media inventory is in `docs/qa/phase19-media-inventory.md`, covering route, asset/URL, local/remote class, natural/rendered dimensions, fold position, loading behavior and action.')
add(7,'REMOTE IMAGE AUDIT','Existing rendered third-party photography remains bounded to the disclosed Unsplash use. No remote image was copied into the repository and no provenance was manufactured.')
add(8,'UNSPLASH DECISIONS','KEEP existing remote assets. CSS variants remain width-parameterized (`w=1800` desktop, `w=1200` mobile) with format negotiation. The obsolete homepage preload was removed because it duplicated the protected poster photograph request.')
add(9,'RESPONSIVE IMAGE DECISIONS','Existing `<img>` assets already carry intrinsic dimensions; below-fold images retain native lazy loading. CSS Unsplash backgrounds retain the existing responsive width switch. Protected film poster remains fixed by lock and is reported separately.')
add(10,'LAZY / EAGER LOADING DECISIONS','First-view/LCP media remains eager/background as appropriate. Below-fold `<img>` imagery remains lazy. Technology hero SVG remains eager/high-priority. Film remains `preload="metadata"`.')
add(11,'PRELOAD / PRECONNECT DECISIONS','Removed a duplicated Unsplash image preload and redundant `dns-prefetch`; retained the stronger Unsplash `preconnect` on the homepage because the protected first-view poster uses that host.')
add(12,'CLS / INTRINSIC-SIZE AUDIT','PASS. All rendered `<img>` elements retain explicit width/height; representative post-change CLS is recorded in the route table. No approved crop behavior was altered.')
add(13,'CSS DELIVERY AUDIT','PASS. `assets/site.css` now contains the exact three formerly imported stylesheets in the same named cascade layers. This removes three blocking dependency requests without aggressive CSS purging; original source files remain untouched for traceability.')
add(14,'JAVASCRIPT DELIVERY AUDIT','PASS. `assets/site.js` and `assets/products-data.js` were not modified. No framework/bundler introduced; Phase 18 static SEO architecture remains intact.')
add(15,'FONT AUDIT','PASS. System font stack retained; remote font requests remain zero; no Google Fonts or new font assets introduced.')
add(16,'FILM PERFORMANCE AUDIT','`PHASE19-FILM-PERFORMANCE-001`: protected film poster is still fixed at Unsplash `w=2000` on mobile; changing it would alter protected markup, so it was not changed. The protected MP4 is ~43.8 MB and was not recompressed. Local Python serving did not prove production HTTP range behavior, so production range efficiency is not asserted.')
add(17,'FILM HASH LOCK','PASS — protected player CSS, hero/player markup and player behavior are preserved by `qa-site`. BROWSER FILM CONTROL QA: normal muted playback and reduced-motion paused gate passed. PRIOR REAL-DEVICE APPROVAL: CARRIED FORWARD; no new real-device claim.')
a=s['afterAxe']; add(18,'AUTOMATED ACCESSIBILITY RESULTS',f"Phase 19 accessibility QA target passed. 32 axe contexts: CRITICAL={a['critical']}, SERIOUS={a['serious']}, MODERATE={a['moderate']}, MINOR={a['minor']}. This is an engineering QA result, not a WCAG certification claim.")
add(19,'KEYBOARD QA',f"PASS. 32 baseline/final traversal contexts show no hidden or zero-size focus targets. Compact navigation open, focus containment, Escape close and focus restoration passed on all {g['summary']['keyboardMenuCases']} route cases.")
add(20,'SKIP-LINK DECISION','KEEP existing skip link. It is the first meaningful keyboard focus on all 16 routes, targets `#main`, becomes visible on focus and passed activation checks. No duplicate skip mechanism added.')
add(21,'LANDMARK QA','PASS. Exactly one `main` per route. The homepage Evidence Axis preview was changed from nested `<aside>` to a labeled `role="group"`, removing the baseline complementary-landmark violation without visual/content change.')
add(22,'HEADING QA','PASS. Exactly one meaningful H1 per route; no SEO-driven heading rewrite introduced.')
add(23,'LINK / BUTTON SEMANTICS','PASS in automated/static review. Navigation remains anchors, actions remain buttons where applicable, menu control retains button semantics, and RFQ handoff remains an anchor to generated `mailto:`.')
add(24,'ALT-TEXT AUDIT','PASS. Every rendered `<img>` retains an alt attribute and intrinsic dimensions. Decorative assets remain empty-alt where already classified; no marketing claims were added to alt text.')
add(25,'CONTRAST QA','PASS. Baseline had serious `color-contrast` findings in all 32 axe contexts. Narrow selector-level corrections were applied to failing small metadata/body labels; brand colors were not globally replaced. Final serious count is zero.')
add(26,'FOCUS QA','PASS. Existing focus-visible treatments were preserved; keyboard traversal found no hidden/zero-size focus targets. Menu and skip-link focus behavior passed.')
locked=len((g.get('film') or {}).get('lockedTouchTargets',[])); add(27,'TOUCH-TARGET QA',f"Primary mobile controls/routes passed structural regression. {locked} film-control measurement(s) remain below the ~44px preference; they are protected by the film hash lock and are reported, not altered. Inline prose links were not misclassified as button targets.")
add(28,'200% ZOOM / REFLOW QA',f"PASS. {g['summary']['zoomCases']} representative routes tested at an effective 720-CSS-pixel viewport corresponding to 1440px at 200% reflow; failures={g['summary']['zoomFailures']}.")
add(29,'TEXT-SPACING QA',f"PASS. {g['summary']['textSpacingCases']} representative routes tested with WCAG-style line/paragraph/letter/word spacing overrides; clipping/overflow failures={g['summary']['textSpacingFailures']}.")
add(30,'REDUCED-MOTION QA','PASS. Protected reduced-motion film gate remains paused near 00:00; decorative motion behavior was not made essential and film logic was not rewritten.')
add(31,'FORCED-COLORS QA',f"PASS functional smoke on {g['summary']['forcedColorsCases']} representative interactive routes; failures={g['summary']['forcedColorsFailures']}. Branding fidelity is not asserted in forced colors; controls/function remain available.")
add(32,'RFQ ACCESSIBILITY REGRESSION','PASS. Labels/fields associated, fields keyboard-accessible, long-input generated mailto retained content, reset cleared fields, mobile layout had no page overflow, and no backend/fake submit behavior was introduced.')
add(33,'PHASE 18 SEO / SOCIAL REGRESSION','PASS: `node scripts/qa-seo.mjs`. 14 indexable / 2 noindex, titles, descriptions, canonicals, robots, sitemap, JSON-LD boundaries and no-sameAs rules preserved.')
add(34,'SOCIAL-CARD LOCK','PASS. Five Phase 18 local cards unchanged; no mapping/redesign/recompression. Approved title/chevron safe-zone remains inherited (minimum 59px).')
add(35,'PHASE 17 PRIVACY / LEGAL REGRESSION',f"PASS. {g['summary']['legalCases']} mobile cases; failures={g['summary']['legalFailures']}. No legal conclusion or privacy wording was changed.")
add(36,'CORE PRODUCT REGRESSION',f"PASS. {g['summary']['coreCases']} mobile core-product cases; failures={g['summary']['coreFailures']}. REFERENCE DETAIL=3 / INQUIRY DETAIL=62 / INVALID=0 and locked technical values retained.")
add(37,'EVIDENCE AXIS / VENTURES REGRESSION',f"PASS. {g['summary']['evidenceVenturesCases']} mobile status cases; failures={g['summary']['evidenceVenturesFailures']}. Evidence Axis specialist-venture and YEKI HAST development-stage wording retained.")
add(38,'32 SITE-WIDE ACCESSIBILITY CONTEXTS',f"PASS. Contexts={a['contexts']}; critical={a['critical']}; serious={a['serious']}.")
add(39,'32 SITE-WIDE SMOKE CASES',f"PASS. Cases={g['summary']['smokeCases']}; failures={g['summary']['smokeFailures']}.")
add(40,'30 REPRESENTATIVE FIVE-VIEWPORT CASES',f"PASS. Cases={g['summary']['representativeCases']}; failures={g['summary']['representativeFailures']}. Screenshots included.")
add(41,'TECHNICAL QA','PASS: `node scripts/qa-site.mjs`, `node scripts/qa-seo.mjs`, `node scripts/qa-performance.mjs`, `node scripts/qa-accessibility.mjs`, browser regression suite. Phase 09–18 locks and protected film hashes preserved.')
mods=[(k,v) for k,v in []]; add(42,'MODERATE / MINOR ACCESSIBILITY FINDINGS',f"Final axe: moderate={a['moderate']}, minor={a['minor']}. Detailed per-context results and any remaining items are in `docs/qa/phase19-accessibility-audit.md`.")
add(43,'PRIVACY-DISCLOSURE IMPACT','NONE. Third-party media host/class and rendered route classes were not materially expanded or localized. Removing a duplicate request does not stale the Phase 17 privacy disclosure.')
add(44,'PERFORMANCE LIMITATIONS','Local synthetic timings vary; no statistical speedup claim. Production CDN/cache/HTTP2/HTTP3 and film range behavior were not established by the local Python server. HTTPS remains a separate release blocker.')
add(45,'ACCESSIBILITY LIMITATIONS','Automated axe + browser/keyboard/reflow/text-spacing/forced-colors QA cannot establish legal WCAG certification or cover every assistive-technology/device combination. Film controls remain constrained by the protected implementation lock.')
add(46,'RELEASE-BLOCKER-HTTPS-001 STATUS','OPEN — CUSTOM DOMAIN HTTPS / “NOT SECURE”. No DNS/CNAME/certificate/canonical transport changes made.')
add(47,'LEGAL-PRIVACY-001 STATUS','OPEN / LEGAL REVIEW REQUIRED.')
add(48,'LEGAL-PRIVACY-002 STATUS','OPEN / LEGAL REVIEW REQUIRED.')
add(49,'SCREENSHOTS / ARTIFACT','Artifact contains before/after raw browser reports, 30 representative screenshots, core/evidence/legal regressions, zoom/text-spacing/forced-colors captures, three audit documents, logs, commit metadata and SHA256 manifest.')
add(50,'rebuild branch SHA',f'`{rebuild}`')
add(51,'main SHA',f'`{main}`')
lines += ['PHASE 20: NOT STARTED','', 'MAIN MERGE: NOT PERFORMED','', 'PRODUCTION DEPLOYMENT: NOT PERFORMED','', 'WAITING FOR: REVIEWER APPROVED PHASE 19','']
(P/'PHASE_19_REVIEW_PACKET.md').write_text('\n'.join(lines),encoding='utf-8')
