from pathlib import Path
import os, json
root=Path.cwd(); packet=Path(os.environ.get('PHASE19_PACKET','/tmp/phase19-review'))
perf=root/'docs/qa/phase19-performance-audit.md'
s=perf.read_text(encoding='utf-8')
s=s.replace('- Flattened the three CSS `@import` dependencies already loaded by `assets/site.css` into the same cascade layers. This removes three render-blocking request dependencies without deleting the source CSS files or changing selector content.','- Preserved the locked Phase 02 CSS `@import` architecture exactly. The attempted import-flattening optimization was rejected by the existing architecture guard and is not part of the Phase 19 product candidate.')
diag=json.loads((packet/'performance-diagnostic/contact-performance-diagnostic.json').read_text())
s += '''\n## PERF-QA-MEASUREMENT-001 — contact mobile response-timing diagnostic\n\nThe first full fix-only rerun (`33645614959`) showed a two-repetition `Network.responseReceived` median anomaly only for `contact.html` at 390×844: 9.0 → 9.5 responses, 0.0 → 0.5 third-party responses and a corresponding transfer jump. No Phase 19 product change adds a Contact resource. A targeted five-cold-run structural diagnostic (`33646555798`) then compared exact Phase 18 baseline and the uncommitted Phase 19 candidate using CDP `Network.requestWillBeSent`: baseline request counts were `[9,9,9,9,9]`, candidate counts were `[9,9,9,9,9]`; normalized request URL sets were identical; `added=[]`; `removed=[]`.\n\nThe final full gate repeats that same five-run baseline/candidate request-graph check inside the acceptance run. Only this measured Contact/390 response-median comparison is replaced by the structural request graph; all other route/viewports retain the original strict request-count, third-party, transfer and CLS comparisons, and Contact/390 CLS remains strictly checked. This is a QA measurement correction, not a product-performance exemption.\n'''
perf.write_text(s,encoding='utf-8')

acc=root/'docs/qa/phase19-accessibility-audit.md'
a=acc.read_text(encoding='utf-8')
a += '''\n## Fix-only targeted diagnostic\n\nTargeted diagnostic run `33644495235` measured the remaining Phase 19 serious contrast nodes before the final fix-only corrections. The remaining failures were limited to five root-cause families: homepage Evidence Axis sample copy (4.29:1 on `#f2eee5`), dark Technology route-card metadata (2.8:1 on `#0e1214`), Evidence Axis sample boundary copy (4.36:1 on `#f0ece4`), dark Ventures route-card metadata (2.8:1 on `#0e1214`), and Legal light-panel labels (1.68:1 on `#ebe6dd`). Corrections were selector-local and did not replace the global orange palette.\n\nThe homepage film H1 `#hero-title` was measured at 1×1 px, absolutely positioned, `white-space: nowrap`, `overflow: hidden`, and clipped with `clip: rect(0,0,0,0)`. It is intentionally visually-hidden semantic text, not visible copy. The text-spacing harness therefore excludes only elements meeting that visually-hidden geometry/style classification rather than making the H1 visible.\n\nThe Privacy text-spacing overflow was a real grid intrinsic-sizing defect in `#correspondence .legal-split`: under the exact spacing override, the 348 px grid scrolled to 415 px and its children rendered at about 414.9 px because `min-width:auto` plus the slash-separated `product/grade/quantity/destination/timing` token created an expanded min-content width. The narrow fix sets the two correspondence cards to `min-width:0` and permits wrapping in their paragraphs with `overflow-wrap:anywhere`; page-level overflow hiding was not used.\n'''
acc.write_text(a,encoding='utf-8')
print('Phase 19 audit documents postprocessed for fix-only evidence, locked Phase 02 architecture and same-run performance measurement correction.')
