const fs=require('fs'),path=require('path'),puppeteer=require('puppeteer-core'),axe=require('axe-core');
const BASE='http://127.0.0.1:8000/';
const OUT=process.env.PHASE19_DIAG_OUT||'/tmp/phase19-targeted';
const routes=['index.html','corporate.html','energy.html','products.html','product.html','urea-46.html','caustic-soda-solid.html','sodium-sulphate-anhydrous.html','sales.html','technology.html','evidence-axis.html','ventures.html','contact.html','privacy.html','legal.html','404.html'];
const views=[[1440,900],[390,844]];
fs.mkdirSync(OUT,{recursive:true});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function firstCheckData(node){for(const group of ['any','all','none'])for(const c of node[group]||[])if(c.id==='contrast'||c.data?.contrastRatio!=null||c.data?.fgColor)return c.data||{};return{};}
function cssPath(el){if(!el)return null;if(el.id)return '#'+CSS.escape(el.id);const parts=[];for(let e=el;e&&e.nodeType===1&&e!==document.documentElement;e=e.parentElement){let p=e.localName;if(e.classList.length)p+='.'+[...e.classList].slice(0,3).map(x=>CSS.escape(x)).join('.');if(e.parentElement){const same=[...e.parentElement.children].filter(x=>x.localName===e.localName);if(same.length>1)p+=`:nth-of-type(${same.indexOf(e)+1})`;}parts.unshift(p);if(parts.length>=6)break;}return parts.join(' > ');}
async function axeDiagnostic(browser,route,w,h){const ctx=await browser.createBrowserContext();const page=await ctx.newPage();await page.setViewport({width:w,height:h});await page.goto(BASE+route,{waitUntil:'load',timeout:45000});await sleep(350);await page.addScriptTag({content:axe.source});const rows=await page.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'rule',values:['color-contrast']},resultTypes:['violations']});const out=[];for(const v of r.violations){for(const n of v.nodes){let el=null;try{el=document.querySelector(n.target[0])}catch{};const cs=el?getComputedStyle(el):null;let data={};for(const group of ['any','all','none'])for(const c of n[group]||[])if(c.id==='contrast'||c.data?.contrastRatio!=null||c.data?.fgColor){data=c.data||{};break;}out.push({rule:v.id,impact:v.impact,target:n.target,selector:(()=>{if(!el)return n.target.join(' ');if(el.id)return '#'+CSS.escape(el.id);const parts=[];for(let e=el;e&&e.nodeType===1&&e!==document.documentElement;e=e.parentElement){let p=e.localName;if(e.classList.length)p+='.'+[...e.classList].slice(0,3).map(x=>CSS.escape(x)).join('.');if(e.parentElement){const same=[...e.parentElement.children].filter(x=>x.localName===e.localName);if(same.length>1)p+=`:nth-of-type(${same.indexOf(e)+1})`;}parts.unshift(p);if(parts.length>=6)break;}return parts.join(' > ');})(),text:el?((el.textContent||'').trim().replace(/\s+/g,' ').slice(0,180)):'',foreground:data.fgColor||cs?.color||null,background:data.bgColor||cs?.backgroundColor||null,contrastRatio:data.contrastRatio??null,requiredRatio:data.expectedContrastRatio??null,fontSize:data.fontSize||cs?.fontSize||null,fontWeight:data.fontWeight||cs?.fontWeight||null,computedColor:cs?.color||null,computedBackground:cs?.backgroundColor||null,html:n.html,failureSummary:n.failureSummary});}}
return out;});await ctx.close();return rows.map(x=>({route,viewport:`${w}x${h}`,...x}));}
async function spacingDiagnostic(browser){const style='p{line-height:1.5!important;margin-bottom:2em!important}body,button,input,textarea,select,a{letter-spacing:.12em!important;word-spacing:.16em!important}';
const result={};
for(const route of ['index.html','privacy.html']){const ctx=await browser.createBrowserContext();const page=await ctx.newPage();await page.setViewport({width:390,height:844});await page.goto(BASE+route,{waitUntil:'load',timeout:45000});await page.addStyleTag({content:style});await sleep(150);
if(route==='index.html'){result.index=await page.evaluate(()=>{const e=document.querySelector('main h1');const s=getComputedStyle(e),r=e.getBoundingClientRect();return{selector:'#'+e.id,tag:e.tagName,text:e.textContent.trim(),clientWidth:e.clientWidth,scrollWidth:e.scrollWidth,clientHeight:e.clientHeight,scrollHeight:e.scrollHeight,rect:{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom},position:s.position,width:s.width,height:s.height,minWidth:s.minWidth,maxWidth:s.maxWidth,minHeight:s.minHeight,maxHeight:s.maxHeight,whiteSpace:s.whiteSpace,overflow:s.overflow,overflowX:s.overflowX,overflowY:s.overflowY,clip:s.clip,clipPath:s.clipPath,display:s.display,visibility:s.visibility,opacity:s.opacity,ariaHidden:e.getAttribute('aria-hidden'),role:e.getAttribute('role'),visuallyHidden:((r.width<=1.5&&r.height<=1.5)||(s.clip&&s.clip!=='auto')||(s.clipPath&&s.clipPath!=='none'))};});}
else{result.privacy=await page.evaluate(()=>{const de=document.documentElement;const nodes=[...document.body.querySelectorAll('*')].map(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);const overflowRight=r.right-de.clientWidth,overflowLeft=-r.left;const own=e.scrollWidth>e.clientWidth+1;const geo=overflowRight>1||overflowLeft>1;return{e,r,s,own,geo,overflowRight,overflowLeft}}).filter(x=>x.own||x.geo).sort((a,b)=>Math.max(b.overflowRight,b.e.scrollWidth-b.e.clientWidth)-Math.max(a.overflowRight,a.e.scrollWidth-a.e.clientWidth)).slice(0,25).map(x=>({selector:(()=>{const e=x.e;if(e.id)return '#'+CSS.escape(e.id);const p=[];for(let n=e;n&&n!==document.documentElement;n=n.parentElement){let q=n.localName;if(n.classList.length)q+='.'+[...n.classList].slice(0,3).map(c=>CSS.escape(c)).join('.');if(n.parentElement){const same=[...n.parentElement.children].filter(c=>c.localName===n.localName);if(same.length>1)q+=`:nth-of-type(${same.indexOf(n)+1})`;}p.unshift(q);if(p.length>=6)break;}return p.join(' > ');})(),clientWidth:x.e.clientWidth,scrollWidth:x.e.scrollWidth,rect:{x:x.r.x,y:x.r.y,width:x.r.width,height:x.r.height,right:x.r.right,bottom:x.r.bottom},text:(x.e.textContent||x.e.value||'').trim().replace(/\s+/g,' ').slice(0,220),whiteSpace:x.s.whiteSpace,overflowWrap:x.s.overflowWrap,wordBreak:x.s.wordBreak,display:x.s.display,width:x.s.width,maxWidth:x.s.maxWidth,minWidth:x.s.minWidth,overflowX:x.s.overflowX,overflowRight:x.overflowRight,overflowLeft:x.overflowLeft,ownScrollOverflow:x.own}));return{clientWidth:de.clientWidth,scrollWidth:de.scrollWidth,overflow:de.scrollWidth>de.clientWidth+1,nodes};});}
await ctx.close();}
return result;}
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const contrast=[];let spacing;try{for(const route of routes)for(const [w,h] of views)contrast.push(...await axeDiagnostic(browser,route,w,h));spacing=await spacingDiagnostic(browser);}finally{await browser.close();}const report={contrastCount:contrast.length,contrast,spacing};fs.writeFileSync(path.join(OUT,'phase19-targeted-diagnostic.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));})();
