const fs=require('fs'),path=require('path'),puppeteer=require('puppeteer-core'),axe=require('axe-core');
const BASE='http://127.0.0.1:8000/';
const OUT=process.env.PHASE19_VERIFY_OUT||'/tmp/phase19-targeted-verify';
const routes=['index.html','corporate.html','energy.html','products.html','product.html','urea-46.html','caustic-soda-solid.html','sodium-sulphate-anhydrous.html','sales.html','technology.html','evidence-axis.html','ventures.html','contact.html','privacy.html','legal.html','404.html'];
const spacingRoutes=['index.html','products.html','sales.html','technology.html','contact.html','privacy.html','legal.html'];
const views=[[1440,900],[390,844]];fs.mkdirSync(OUT,{recursive:true});const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function axeOne(browser,route,w,h){const ctx=await browser.createBrowserContext();const page=await ctx.newPage();await page.setViewport({width:w,height:h});await page.goto(BASE+route,{waitUntil:'load',timeout:45000});await sleep(250);await page.addScriptTag({content:axe.source});const r=await page.evaluate(async()=>{const z=await axe.run(document,{resultTypes:['violations']});return z.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>({target:n.target,html:n.html,failureSummary:n.failureSummary}))}))});await ctx.close();return{route,viewport:`${w}x${h}`,violations:r};}
async function spacingOne(browser,route){const ctx=await browser.createBrowserContext();const page=await ctx.newPage();await page.setViewport({width:390,height:844});await page.goto(BASE+route,{waitUntil:'load',timeout:45000});await page.addStyleTag({content:'p{line-height:1.5!important;margin-bottom:2em!important}body,button,input,textarea,select,a{letter-spacing:.12em!important;word-spacing:.16em!important}'});await sleep(120);const d=await page.evaluate(()=>{const visuallyHidden=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();const clipped=(s.clip&&s.clip!=='auto'&&s.clip!=='rect(auto, auto, auto, auto)')||(s.clipPath&&s.clipPath!=='none');return r.width<=1.5&&r.height<=1.5&&(s.position==='absolute'||s.position==='fixed')&&s.whiteSpace==='nowrap'&&s.overflow==='hidden'&&clipped};const candidates=[...document.querySelectorAll('p,h1,h2,h3,button,a,input,textarea,select')];const excluded=candidates.filter(visuallyHidden).map(e=>({tag:e.tagName,id:e.id||'',text:(e.textContent||e.value||'').trim().slice(0,90)}));const clipped=candidates.filter(e=>{if(visuallyHidden(e))return false;const s=getComputedStyle(e);return s.overflow==='hidden'&&e.scrollHeight>e.clientHeight+2}).map(e=>({tag:e.tagName,id:e.id||'',text:(e.textContent||e.value||'').trim().slice(0,90)}));return{overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+1,clientWidth:document.documentElement.clientWidth,scrollWidth:document.documentElement.scrollWidth,clipped,visuallyHiddenExcluded:excluded}});await ctx.close();return{route,...d,pass:!d.overflow&&d.clipped.length===0};}
(async()=>{const browser=await puppeteer.launch({executablePath:process.env.CHROME,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});const axeResults=[],spacing=[];try{for(const r of routes)for(const [w,h] of views)axeResults.push(await axeOne(browser,r,w,h));for(const r of spacingRoutes)spacing.push(await spacingOne(browser,r));}finally{await browser.close();}const totals={critical:0,serious:0,moderate:0,minor:0};for(const c of axeResults)for(const v of c.violations)if(totals[v.impact]!=null)totals[v.impact]++;const report={accessibilityContexts:axeResults.length,axeTotals:totals,remainingSerious:axeResults.flatMap(c=>c.violations.filter(v=>v.impact==='serious').map(v=>({route:c.route,viewport:c.viewport,...v}))),textSpacingCases:spacing.length,textSpacingPasses:spacing.filter(x=>x.pass).length,textSpacing:spacing};fs.writeFileSync(path.join(OUT,'phase19-targeted-verify.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(totals.critical||totals.serious||spacing.some(x=>!x.pass))process.exit(1);})();
